{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (2.2.2)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas) (1.26.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: scikit-learn in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (1.4.2)\n",
      "Requirement already satisfied: numpy>=1.19.5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn) (1.26.4)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn) (1.13.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn) (1.4.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn) (3.4.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: seaborn in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from seaborn) (1.26.4)\n",
      "Requirement already satisfied: pandas>=1.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from seaborn) (2.2.2)\n",
      "Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from seaborn) (3.8.4)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.0)\n",
      "Requirement already satisfied: pillow>=8 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.3.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas>=1.2->seaborn) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas>=1.2->seaborn) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: dagshub in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (0.3.25)\n",
      "Requirement already satisfied: PyYAML>=5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (6.0.1)\n",
      "Requirement already satisfied: fusepy>=3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (3.0.1)\n",
      "Requirement already satisfied: appdirs>=1.4.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (1.4.4)\n",
      "Requirement already satisfied: click>=8.0.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (8.1.7)\n",
      "Requirement already satisfied: httpx~=0.23.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (0.23.3)\n",
      "Requirement already satisfied: GitPython>=3.1.29 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (3.1.43)\n",
      "Requirement already satisfied: rich~=13.1.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (13.1.0)\n",
      "Requirement already satisfied: dacite~=1.6.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (1.6.0)\n",
      "Requirement already satisfied: tenacity~=8.2.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (8.2.3)\n",
      "Requirement already satisfied: gql[requests] in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (3.5.0)\n",
      "Requirement already satisfied: dataclasses-json in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (0.6.5)\n",
      "Requirement already satisfied: pandas in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (2.2.2)\n",
      "Requirement already satisfied: treelib~=1.6.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (1.6.4)\n",
      "Requirement already satisfied: pathvalidate~=3.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (3.0.0)\n",
      "Requirement already satisfied: python-dateutil in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (2.9.0.post0)\n",
      "Requirement already satisfied: boto3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dagshub) (1.34.93)\n",
      "Requirement already satisfied: colorama in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from click>=8.0.4->dagshub) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from GitPython>=3.1.29->dagshub) (4.0.11)\n",
      "Requirement already satisfied: certifi in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from httpx~=0.23.0->dagshub) (2024.2.2)\n",
      "Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from httpx~=0.23.0->dagshub) (0.16.3)\n",
      "Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from httpx~=0.23.0->dagshub) (1.5.0)\n",
      "Requirement already satisfied: sniffio in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from httpx~=0.23.0->dagshub) (1.3.1)\n",
      "Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from rich~=13.1.0->dagshub) (0.9.1)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from rich~=13.1.0->dagshub) (2.17.2)\n",
      "Requirement already satisfied: six in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from treelib~=1.6.4->dagshub) (1.16.0)\n",
      "Requirement already satisfied: botocore<1.35.0,>=1.34.93 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from boto3->dagshub) (1.34.93)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from boto3->dagshub) (1.0.1)\n",
      "Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from boto3->dagshub) (0.10.1)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dataclasses-json->dagshub) (3.21.1)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from dataclasses-json->dagshub) (0.9.0)\n",
      "Requirement already satisfied: graphql-core<3.3,>=3.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (3.2.3)\n",
      "Requirement already satisfied: yarl<2.0,>=1.6 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (1.9.4)\n",
      "Requirement already satisfied: backoff<3.0,>=1.11.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (2.2.1)\n",
      "Requirement already satisfied: anyio<5,>=3.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (4.3.0)\n",
      "Requirement already satisfied: requests<3,>=2.26 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (2.31.0)\n",
      "Requirement already satisfied: requests-toolbelt<2,>=1.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gql[requests]->dagshub) (1.0.0)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas->dagshub) (1.26.4)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas->dagshub) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas->dagshub) (2024.1)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from anyio<5,>=3.0->gql[requests]->dagshub) (3.7)\n",
      "Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from botocore<1.35.0,>=1.34.93->boto3->dagshub) (2.2.1)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.1)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.0->dagshub) (0.14.0)\n",
      "Requirement already satisfied: packaging>=17.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->dagshub) (24.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from requests<3,>=2.26->gql[requests]->dagshub) (3.3.2)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.0.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (4.11.0)\n",
      "Requirement already satisfied: multidict>=4.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.0.5)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: mlflow in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (2.12.1)\n",
      "Requirement already satisfied: Flask<4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.0.3)\n",
      "Requirement already satisfied: alembic!=1.10.0,<2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (1.13.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (8.1.7)\n",
      "Requirement already satisfied: cloudpickle<4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.0.0)\n",
      "Requirement already satisfied: docker<8,>=4.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (7.0.0)\n",
      "Requirement already satisfied: entrypoints<1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (0.4)\n",
      "Requirement already satisfied: gitpython<4,>=3.1.9 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.1.43)\n",
      "Requirement already satisfied: graphene<4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.3)\n",
      "Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (7.1.0)\n",
      "Requirement already satisfied: markdown<4,>=3.3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.6)\n",
      "Requirement already satisfied: matplotlib<4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.8.4)\n",
      "Requirement already satisfied: numpy<2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (1.26.4)\n",
      "Requirement already satisfied: packaging<25 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (24.0)\n",
      "Requirement already satisfied: pandas<3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (2.2.2)\n",
      "Requirement already satisfied: protobuf<6,>=3.12.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (4.25.3)\n",
      "Requirement already satisfied: pyarrow<16,>=4.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (15.0.2)\n",
      "Requirement already satisfied: pytz<2025 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (2024.1)\n",
      "Requirement already satisfied: pyyaml<7,>=5.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (6.0.1)\n",
      "Requirement already satisfied: querystring-parser<2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (1.2.4)\n",
      "Requirement already satisfied: requests<3,>=2.17.3 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (2.31.0)\n",
      "Requirement already satisfied: scikit-learn<2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (1.4.2)\n",
      "Requirement already satisfied: scipy<2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (1.13.0)\n",
      "Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (2.0.29)\n",
      "Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (0.5.0)\n",
      "Requirement already satisfied: Jinja2<4,>=3.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.1.3)\n",
      "Requirement already satisfied: waitress<4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from mlflow) (3.0.0)\n",
      "Requirement already satisfied: Mako in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.3)\n",
      "Requirement already satisfied: typing-extensions>=4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from alembic!=1.10.0,<2->mlflow) (4.11.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from click<9,>=7.0->mlflow) (0.4.6)\n",
      "Requirement already satisfied: urllib3>=1.26.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from docker<8,>=4.0.0->mlflow) (2.2.1)\n",
      "Requirement already satisfied: pywin32>=304 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from docker<8,>=4.0.0->mlflow) (306)\n",
      "Requirement already satisfied: Werkzeug>=3.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from Flask<4->mlflow) (3.0.2)\n",
      "Requirement already satisfied: itsdangerous>=2.1.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from Flask<4->mlflow) (2.2.0)\n",
      "Requirement already satisfied: blinker>=1.6.2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from Flask<4->mlflow) (1.8.1)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gitpython<4,>=3.1.9->mlflow) (4.0.11)\n",
      "Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from graphene<4->mlflow) (3.2.3)\n",
      "Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from graphene<4->mlflow) (3.2.0)\n",
      "Requirement already satisfied: aniso8601<10,>=8 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from graphene<4->mlflow) (9.0.1)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow) (3.18.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from Jinja2<4,>=3.0->mlflow) (2.1.5)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (1.4.5)\n",
      "Requirement already satisfied: pillow>=8 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (10.3.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from matplotlib<4->mlflow) (2.9.0.post0)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from pandas<3->mlflow) (2024.1)\n",
      "Requirement already satisfied: six in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from querystring-parser<2->mlflow) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from requests<3,>=2.17.3->mlflow) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from requests<3,>=2.17.3->mlflow) (3.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from requests<3,>=2.17.3->mlflow) (2024.2.2)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn<2->mlflow) (1.4.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scikit-learn<2->mlflow) (3.4.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.0.3)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow) (5.0.1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: scipy in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (1.13.0)\n",
      "Requirement already satisfied: numpy<2.3,>=1.22.4 in c:\\users\\jkoenemann\\github\\machine_failure_classification\\venv\\lib\\site-packages (from scipy) (1.26.4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 23.2.1 -> 24.1.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "!{sys.executable} -m pip install pandas\n",
    "!{sys.executable} -m pip install scikit-learn\n",
    "!{sys.executable} -m pip install seaborn\n",
    "!{sys.executable} -m pip install dagshub\n",
    "!{sys.executable} -m pip install mlflow\n",
    "!{sys.executable} -m pip install scipy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import mlflow\n",
    "import mlflow.sklearn\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split, RandomizedSearchCV\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.metrics import f1_score, classification_report, confusion_matrix, make_scorer\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import randint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\">Initialized MLflow to track repo <span style=\"color: #008000; text-decoration-color: #008000\">\"JonaKoenemann/machine_failure_classification\"</span>\n",
       "</pre>\n"
      ],
      "text/plain": [
       "Initialized MLflow to track repo \u001b[32m\"JonaKoenemann/machine_failure_classification\"\u001b[0m\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\">Repository JonaKoenemann/machine_failure_classification initialized!\n",
       "</pre>\n"
      ],
      "text/plain": [
       "Repository JonaKoenemann/machine_failure_classification initialized!\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# set up dagshub for mlflow tracking\n",
    "import dagshub\n",
    "dagshub.init(repo_owner='JonaKoenemann', repo_name='machine_failure_classification', mlflow=True)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Data preparation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_path = \"../../../data/predictive_maintenance.csv\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(data_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "categorical_features = ['Type']\n",
    "numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()\n",
    "numerical_features.remove('UDI')\n",
    "numerical_features.remove('Target')\n",
    "\n",
    "# Feature Engineering: Polynomial Features\n",
    "poly = PolynomialFeatures(degree=2, include_bias=False)\n",
    "\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', Pipeline(steps=[\n",
    "            ('scaler', StandardScaler()),\n",
    "            ('poly', poly)\n",
    "        ]), numerical_features),\n",
    "        ('cat', OneHotEncoder(), categorical_features)\n",
    "    ])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split for features (X) und labels (y)\n",
    "X = df[numerical_features + categorical_features] # select Features \n",
    "y = df[\"Failure Type\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Encode target variable as categorical\n",
    "y_encoded = pd.get_dummies(y).values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split for test and train data\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(8000, 23)\n",
      "(2000, 23)\n"
     ]
    }
   ],
   "source": [
    "# Test preprocessor pipeline\n",
    "X_train_transformed = preprocessor.fit_transform(X_train)\n",
    "X_test_transformed = preprocessor.transform(X_test)\n",
    "\n",
    "print(X_train_transformed.shape)\n",
    "print(X_test_transformed.shape)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Train and test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "mlflow.set_experiment(\"random_forest_rs_feature_encoded\")\n",
    "\n",
    "mlflow.sklearn.autolog()\n",
    "\n",
    "model = RandomForestClassifier(random_state=42)\n",
    "\n",
    "param_distributions = {\n",
    "    'model__n_estimators': randint(100, 250),\n",
    "    'model__max_depth': [None, randint(10, 30)], # None or integer between 10 and 30\n",
    "    'model__min_samples_split': randint(2, 10),\n",
    "    'model__min_samples_leaf': randint(1, 5),\n",
    "    'model__bootstrap': [True, False]\n",
    "}\n",
    "\n",
    "# Define the pipeline\n",
    "pipeline = Pipeline(steps=[\n",
    "    ('preprocessor', preprocessor),\n",
    "    ('model', model)\n",
    "])\n",
    "\n",
    "# weighted f1 score as scoring metric\n",
    "scorer = make_scorer(f1_score, average = \"weighted\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/07/04 18:42:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\mlflow\\data\\digest_utils.py:26: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\"\n",
      "2024/07/04 18:43:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\mlflow\\types\\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 3 folds for each of 50 candidates, totalling 150 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py:547: FitFailedWarning: \n",
      "60 fits failed out of a total of 150.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A20C8B470> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D5DAD610> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000261E130B6E0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A210E4E90> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A22AECB30> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A210E4F80> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA5D826C0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000186FA988CB0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA5D807D0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FECC32D190> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FECC32DA30> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FECE62BEF0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D53C6150> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D4D57E90> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D6437CB0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D7C0DF10> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D5B7A3C0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D754F1A0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D5DAD4F0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D7C0E570> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB533B110> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2A5DE50> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2A5E000> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB51A82C0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2A5E090> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB3AD7CB0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB3161FA0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB51A9430> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2BAB5C0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB4C0E4E0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB324C080> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB5312AB0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB51AA480> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2E0B950> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB2A5E660> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AAFFD9040> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB4F737A0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A1DE8D880> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A22E55E50> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A230557F0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000261E1CD7AA0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000261E34C13A0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000261E130B470> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D53C6C90> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002B7D7C425A0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A21387CB0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000016A210B83B0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA59263C0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA7CF35F0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB5173230> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA78D00B0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000025AB37D3500> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000013BA63302F0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FECE54E360> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FEC6F9D2B0> instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\pipeline.py\", line 475, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 1467, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\base.py\", line 666, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'max_depth' parameter of RandomForestClassifier must be an int in the range [1, inf) or None. Got <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001FECCE9D5B0> instead.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\model_selection\\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan 0.97831389 0.97433193        nan 0.97792853        nan\n",
      " 0.97702406 0.97443953        nan 0.97637207 0.97430197        nan\n",
      "        nan        nan 0.97650413 0.97499125        nan        nan\n",
      "        nan        nan        nan        nan 0.97504904 0.97433193\n",
      "        nan 0.9750659  0.97473858 0.97851824 0.97722267 0.97698453\n",
      " 0.97701066        nan 0.97794635 0.97399216        nan 0.97853481\n",
      "        nan 0.97404961 0.97556902 0.97800822        nan        nan\n",
      " 0.97524186 0.97510763 0.97404546 0.97822532        nan 0.97875089\n",
      " 0.97783608 0.97402   ]\n",
      "  warnings.warn(\n",
      "2024/07/04 18:46:43 WARNING mlflow.sklearn.utils: log_loss failed. The metric training_log_loss will not be recorded. Metric error: Found array with dim 3. None expected <= 2.\n",
      "2024/07/04 18:46:43 WARNING mlflow.sklearn.utils: roc_auc_score failed. The metric training_roc_auc will not be recorded. Metric error: Found array with dim 3. None expected <= 2.\n",
      "2024/07/04 18:46:43 WARNING mlflow.sklearn.utils: Failed to autolog artifacts for RandomizedSearchCV. Logging error: unhashable type: 'numpy.ndarray'\n",
      "2024/07/04 18:46:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: \"c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\mlflow\\types\\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.\"\n",
      "2024/07/04 18:47:08 INFO mlflow.sklearn.utils: Logging the 5 best runs, 45 runs will be omitted.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "best params: {'model__bootstrap': False, 'model__max_depth': None, 'model__min_samples_leaf': 2, 'model__min_samples_split': 5, 'model__n_estimators': 111}\n",
      "\n",
      "weighted f1 score: 0.9784958692183203\n"
     ]
    }
   ],
   "source": [
    "with mlflow.start_run():    \n",
    "    # Set up RandomizedSearchCV\n",
    "    randomized_search = RandomizedSearchCV(estimator=pipeline, param_distributions=param_distributions,\n",
    "                                           n_iter=50, cv=3, verbose=2, random_state=42, n_jobs=-1, scoring=scorer)\n",
    "\n",
    "    # Fit RandomizedSearchCV\n",
    "    randomized_search.fit(X_train, y_train)\n",
    "\n",
    "    # Get the best parameters\n",
    "    best_params = randomized_search.best_params_\n",
    "    mlflow.log_params(best_params)\n",
    "    print(f\"\\nbest params: {best_params}\")\n",
    "\n",
    "    # Get the best model\n",
    "    best_model = randomized_search.best_estimator_\n",
    "\n",
    "    # predicition\n",
    "    y_pred = best_model.predict(X_test)\n",
    "\n",
    "    # evaluation\n",
    "    weighted_f1 = f1_score(y_true = y_test, y_pred= y_pred, average=\"weighted\")\n",
    "    print(\"\\nweighted f1 score:\", weighted_f1)\n",
    "    mlflow.log_metric('weighted_f1_score', weighted_f1)\n",
    "    \n",
    "    mlflow.end_run()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Evaluation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "error_names = [\n",
    " 'Heat Failure',\n",
    " 'No Failure',\n",
    " 'Overstrain Failure',\n",
    " 'Power Failure',\n",
    " 'Random Failure',\n",
    " 'Tool wear Failure'] # get names of errors in correct order for confusion matrix"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Classification report"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Classification Report:\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.92      0.80      0.86        15\n",
      "           1       0.99      1.00      0.99      1935\n",
      "           2       0.88      0.54      0.67        13\n",
      "           3       0.84      0.80      0.82        20\n",
      "           4       0.00      0.00      0.00         6\n",
      "           5       0.00      0.00      0.00        11\n",
      "\n",
      "   micro avg       0.99      0.98      0.98      2000\n",
      "   macro avg       0.60      0.52      0.56      2000\n",
      "weighted avg       0.98      0.98      0.98      2000\n",
      " samples avg       0.98      0.98      0.98      2000\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "c:\\Users\\jkoenemann\\GitHub\\machine_failure_classification\\venv\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n"
     ]
    }
   ],
   "source": [
    "print(\"Classification Report:\")\n",
    "report = classification_report(y_test, y_pred)\n",
    "print(report)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Normalized confusion matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAxgAAAKQCAYAAAAc6dxlAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAACaXElEQVR4nOzdd3QU1f/G8WeTkAQIqQRCTQKEHpqo9BJAiqhBRFSkiiAW4IsgXapEEKkqUpQugnQBFURBAaVKQDqhiYSSBoSShGR/f/BjZUkCCQzshrxf5+w5zN2Z2c/szYQ8O/fOmsxms1kAAAAAYAAHWxcAAAAA4PFBwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAA8VPXq1VO9evUsyydOnJDJZNKsWbMeaR0dOnRQQEDAI33N+zV37lyVLl1aOXLkkKenp+H7Hzp0qEwmk+H7zaps9TMJPK4IGABgY7NmzZLJZJKrq6v+/fffVM/Xq1dP5cuXt0Fl2duyZcvUtGlT5c2bV87OzipYsKBefvll/fLLLw/1dQ8ePKgOHTqoePHimj59uqZNm/ZQX+9RM5lMMplM6ty5c5rPDxw40LJOVFRUpve/Zs0aDR069AGrBPAgCBgAYCcSEhL08ccf27qMh87f31/Xrl1T27ZtbV1Kmsxmszp27KgXX3xR586dU69evfTll1/qnXfe0bFjx9SgQQNt2bLlob3+hg0blJKSookTJ6pDhw56+eWXDX+NQYMG6dq1a4bvN6NcXV21ZMkSJSYmpnpuwYIFcnV1ve99r1mzRsOGDcvUNvb+MwlkNQQMALATlSpV0vTp03XmzJmH9hpms9mmf1hKslytcXR0tGkd6fn00081a9Ys9ezZUzt37tSAAQPUqVMnDRw4UDt27NCcOXPk5OT00F7//PnzkvRQhkbd4uTk9EB/xD+oJk2a6NKlS/rhhx+s2rds2aLjx4/r2WeffSR13LhxQ4mJiXb/MwlkNQQMALATAwYMUHJycoauYty4cUMjRoxQ8eLF5eLiooCAAA0YMEAJCQlW6wUEBKh58+b66aefVLVqVeXMmVNTp07Vhg0bZDKZtGjRIg0bNkyFChVSnjx59NJLL+nixYtKSEhQz549lS9fPrm5ualjx46p9j1z5kyFhIQoX758cnFxUdmyZTVlypR71n7nePdbtaT1uHPOxA8//KDatWsrd+7cypMnj5599lnt27cv1WssX75c5cuXl6urq8qXL69ly5bdsy5JunbtmsLCwlS6dGmNHTs2zXkKbdu21VNPPWVZPnbsmFq1aiVvb2/lypVL1apV0+rVq622uf39/uijj1S4cGG5urqqQYMGOnr0qGW9gIAADRkyRJLk6+srk8lkGe5z+79vFxAQoA4dOliWk5KSNGzYMAUFBcnV1VU+Pj6qVauW1q1bZ1knrTkYmf2Z2rRpk5566im5urqqWLFimjNnzt3f3NsUKlRIderU0TfffGPVPn/+fAUHB6c5JPD3339Xq1atVLRoUbm4uKhIkSL63//+ZxWYO3TooM8//9zyft16SP/93I0dO1YTJkywHOf+/ftT/UyeP39evr6+qlevnsxms2X/R48eVe7cudW6desMHyuQHT28j2AAAJkSGBiodu3aafr06erXr58KFiyY7rqdO3fW7Nmz9dJLL+n999/X1q1bFRYWpgMHDqT6Y/rQoUN69dVX1bVrV7355psqVaqU5bmwsDDlzJlT/fr109GjRzV58mTlyJFDDg4Oio2N1dChQ/Xnn39q1qxZCgwM1IcffmjZdsqUKSpXrpyef/55OTk56fvvv9fbb7+tlJQUvfPOOxk+7jJlymju3LlWbXFxcerVq5fy5ctnaZs7d67at2+vxo0ba/To0bp69aqmTJmiWrVq6a+//rKEkbVr16ply5YqW7aswsLCFB0drY4dO6pw4cL3rGXTpk2KiYlRz549M/Rp9rlz51SjRg1dvXpV3bt3l4+Pj2bPnq3nn39eixcvVosWLazW//jjj+Xg4KDevXvr4sWLGjNmjNq0aaOtW7dKkiZMmKA5c+Zo2bJlmjJlitzc3FShQoV71nG7oUOHKiwsTJ07d9ZTTz2lS5cuaceOHdq1a5caNWqU7naZ+Zk6evSoXnrpJb3xxhtq3769vv76a3Xo0EFPPPGEypUrl6E6X3vtNfXo0UPx8fFyc3PTjRs39N1336lXr166fv16qvW/++47Xb16Vd26dZOPj4+2bdumyZMn6/Tp0/ruu+8kSV27dtWZM2e0bt26VD9Tt8ycOVPXr19Xly5d5OLiIm9vb6WkpFitky9fPk2ZMkWtWrXS5MmT1b17d6WkpKhDhw7KkyePvvjiiwwdI5BtmQEANjVz5kyzJPP27dvNERERZicnJ3P37t0tz9etW9dcrlw5y/Lu3bvNksydO3e22k/v3r3Nksy//PKLpc3f398syfzjjz9arfvrr7+aJZnLly9vTkxMtLS/+uqrZpPJZG7atKnV+tWrVzf7+/tbtV29ejXVsTRu3NhcrFgxq7a6deua69ata1k+fvy4WZJ55syZab4fKSkp5ubNm5vd3NzM+/btM5vNZvPly5fNnp6e5jfffNNq3bNnz5o9PDys2itVqmQuUKCAOS4uztK2du1as6RUx3CniRMnmiWZly1bdtf1bunZs6dZkvn333+3tF2+fNkcGBhoDggIMCcnJ5vN5v/e7zJlypgTEhJSvd7evXstbUOGDDFLMl+4cMHqtSSZhwwZkqoGf39/c/v27S3LFStWND/77LN3rfvWa9xyPz9Tv/32m6Xt/PnzZhcXF/P7779/19e9dRzvvPOOOSYmxuzs7GyeO3eu2Ww2m1evXm02mUzmEydOpPkepPXzFhYWZjaZTOaTJ09a2t555x1zWn/e3Pq5c3d3N58/fz7N5+78mXz11VfNuXLlMh8+fNj8ySefmCWZly9ffs9jBLI7hkgBgB0pVqyY2rZtq2nTpikyMjLNddasWSNJ6tWrl1X7+++/L0mphucEBgaqcePGae6rXbt2ypEjh2X56aefltlsVqdOnazWe/rpp/XPP//oxo0blracOXNa/n3x4kVFRUWpbt26OnbsmC5evHivQ03XiBEjtGrVKs2aNUtly5aVJK1bt05xcXF69dVXFRUVZXk4Ojrq6aef1q+//ipJioyM1O7du9W+fXt5eHhY9tmoUSPLvu7m0qVLkqQ8efJkqNY1a9boqaeeUq1atSxtbm5u6tKli06cOKH9+/dbrd+xY0c5OztblmvXri3p5jAro3h6emrfvn06cuRIhrfJ7M9U2bJlLbVLN4dzlSpVKlPH4eXlpSZNmmjBggWSpG+++UY1atSQv79/muvf/vN25coVRUVFqUaNGjKbzfrrr78y/LotW7aUr69vhtb97LPP5OHhoZdeekmDBw9W27Zt9cILL2T4tYDsioABAHZm0KBBunHjRrpzMU6ePCkHBweVKFHCqt3Pz0+enp46efKkVXtgYGC6r1W0aFGr5Vt/lBcpUiRVe0pKilVw2Lx5sxo2bKjcuXPL09NTvr6+GjBggCTdd8D48ccfNWzYMPXv318tW7a0tN/6YzkkJES+vr5Wj7Vr11omRt869qCgoFT7vn1oWHrc3d0lSZcvX85QvSdPnkxzv2XKlLGq55Y7328vLy9JUmxsbIZeLyOGDx+uuLg4lSxZUsHBwerTp4/27Nlz120y+zN153FIN48ls8fx2muvad26dTp16pSWL1+u1157Ld11T506pQ4dOsjb21tubm7y9fVV3bp1JWXu5+1u58OdvL29NWnSJO3Zs0ceHh6aNGlShrcFsjPmYACAnSlWrJhef/11TZs2Tf369Ut3vYx+Udrtn/zeKb15Bum1m/9/wmtERIQaNGig0qVLa9y4cSpSpIicnZ21Zs0ajR8/PtWY9ow4fvy42rRpo0aNGmnkyJFWz93a39y5c+Xn55dqW6Pu6lS6dGlJ0t69exUaGmrIPm93r/f1fiQnJ1st16lTRxEREVqxYoXWrl2rGTNmaPz48fryyy/T/e6JWzL6M2XUcTz//PNycXFR+/btlZCQkO4teZOTk9WoUSPFxMSob9++Kl26tHLnzq1///1XHTp0yNTP293Oh7T89NNPkm6GwNOnTz/Uu3sBjwsCBgDYoUGDBmnevHkaPXp0quf8/f2VkpKiI0eOWD4pl25OOI6Li0t3iImRvv/+eyUkJGjlypVWn2bfGqqUWdeuXdOLL74oT09PLViwQA4O1hfYixcvLunm5NuGDRumu59bx57W8KBDhw7ds45atWrJy8tLCxYs0IABA+450dvf3z/N/R48eNCqHiN4eXkpLi7Oqi0xMTHNoXTe3t7q2LGjOnbsqPj4eNWpU0dDhw5NN2DY6mcqZ86cCg0N1bx58yxfapiWvXv36vDhw5o9e7batWtnab/9zli3GPkN5T/++KNmzJihDz74QPPnz1f79u21devWh3qbYuBxwBApALBDxYsX1+uvv66pU6fq7NmzVs81a9ZM0s07Dt1u3LhxkvRIvkPg1h/et39iffHiRc2cOfO+9vfWW2/p8OHDWrZsmWXY0O0aN24sd3d3jRo1SklJSamev3DhgiSpQIECqlSpkmbPnm01bGbdunWp5kOkJVeuXOrbt68OHDigvn37pvmJ/Lx587Rt2zZJN/ti27Zt+uOPPyzPX7lyRdOmTVNAQECG5n1kVPHixfXbb79ZtU2bNi3VFYzo6GirZTc3N5UoUSLV7WZvZ8ufqd69e2vIkCEaPHhwuuuk9fNmNps1ceLEVOvmzp1bklKFscyKi4uz3Ilr1KhRmjFjhnbt2qVRo0Y90H6B7IAIDgB2auDAgZo7d64OHTpkdevPihUrqn379po2bZri4uJUt25dbdu2TbNnz1ZoaKjq16//0Gt75pln5OzsrOeee05du3ZVfHy8pk+frnz58qU7OT09q1ev1pw5c9SyZUvt2bPHar6Am5ubQkND5e7urilTpqht27aqUqWKXnnlFfn6+urUqVNavXq1atasqc8++0zSzVvvPvvss6pVq5Y6deqkmJgYTZ48WeXKlVN8fPw96+nTp4/27dunTz/9VL/++qteeukl+fn56ezZs1q+fLm2bdtm+Sbvfv36acGCBWratKm6d+8ub29vzZ49W8ePH9eSJUtSXYl5EJ07d9Zbb72lli1bqlGjRgoPD9dPP/2U6lP/smXLql69enriiSfk7e2tHTt2aPHixXr33XfT3bctf6YqVqyoihUr3nWd0qVLq3jx4urdu7f+/fdfubu7a8mSJWnO+XjiiSckSd27d1fjxo3l6OioV155JdN19ejRQ9HR0fr555/l6OioJk2aqHPnzho5cqReeOGFe9YMZGcEDACwUyVKlNDrr7+u2bNnp3puxowZKlasmGbNmqVly5bJz89P/fv3t3xJ28NWqlQpLV68WIMGDVLv3r3l5+enbt26ydfXN9UdqO7l1tWHJUuWaMmSJVbP+fv7W+ZCvPbaaypYsKA+/vhjffLJJ0pISFChQoVUu3ZtdezY0bJNkyZN9N1332nQoEHq37+/ihcvrpkzZ2rFihXasGHDPetxcHDQnDlz9MILL2jatGkaO3asLl26JF9fX9WpU0djxoxR9erVJUn58+fXli1b1LdvX02ePFnXr19XhQoV9P333xv+qf+bb76p48eP66uvvtKPP/6o2rVra926dWrQoIHVet27d9fKlSu1du1aJSQkyN/fXyNHjlSfPn3uun9b/0zdTY4cOfT999+re/fuCgsLk6urq1q0aKF333031R/6L774ot577z19++23mjdvnsxmc6YDxsqVKzVnzhx9+umnlnk50s0rOuvWrVP79u21fft2qzuwAfiPyfwgM8sAAAAA4DbMwQAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAzfgwG74ffmYluXgHT8NLixrUtAOkoVzGPrEgAA2YhrBtIDVzAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMLIZk8mk5cuXS5JOnDghk8mk3bt327QmAAAAPD4IGHfRoUMHhYaGpmrfsGGDTCaT4uLiDHutjO7z1np3PgYNGpSh14mMjFTTpk0NqDh761ivuLaHNdWJL1poTf8QVQ7wuuv6bzYooU0jGuv45y20c3QzDXu5olycOP0ehh9XLNI7rz+nNs1qaMB77XX04N/prvvzmmX68H+d1bFFfXVsUV8jPnj7ruvj4fn2m/lq2ihET1YOVptXWmnvnj22Lgm3oX/sF31jv7Jz3/AXThZ16NAhRUZGWh79+vXL0HZ+fn5ycXExrI7ExETD9pVVvFC1sIa+XEGffr9fz4z4WftOx2lBz9rKmyft97XFU0U0sGWwPv1+v+p8+JN6zd6pF54srP4vln/ElT/+tmxYqzlTx+ul19/U6Cnz5F+spD7q/54uxsakuf7+8J2qWb+xhnzypUZOnCkf3/wa2e9dxUSdf8SVZ28//rBGY8eEqevb7+jb75apVKnS6tb1DUVHR9u6NIj+sWf0jf3K7n1DwDDIpk2bVLt2beXMmVNFihRR9+7ddeXKFcvzc+fOVdWqVZUnTx75+fnptdde0/nzN/+IOXHihOrXry9J8vLykslkUocOHe76evny5ZOfn5/l4ebmpu3bt6tRo0bKmzevPDw8VLduXe3atctqu9uHSN1p1qxZ8vT0tGpbvny5TCaTZXno0KGqVKmSZsyYocDAQLm6ukqS4uLi1LlzZ/n6+srd3V0hISEKDw/PyFuX5XRtVFLzfz+ub7ec1OHIy/pg3i5dS0zWKzUD0lz/yeI+2n40Wsu2/aN/oq9q4/5zWr7tH1UO8H60hWcDq5bMV4Omoarf5HkV9i+mN3v0l7OLq379aWWa63fvP1KNn2+lgBKlVKhogN7qNUhms1l7/9r2iCvP3ubOnqkXX3pZoS1aqniJEho0ZJhcXV21fOkSW5cG0T/2jL6xX9m9bwgYBoiIiFCTJk3UsmVL7dmzRwsXLtSmTZv07rvvWtZJSkrSiBEjFB4eruXLl+vEiROWEFGkSBEtWXLzB+7WlYmJEydmuo7Lly+rffv22rRpk/78808FBQWpWbNmunz5siHHecvRo0e1ZMkSLV261DJ/o1WrVjp//rx++OEH7dy5U1WqVFGDBg0UE5P2J8dZVQ5Hkyr4e+q3A/99wm02S78fOKeqxX3S3GZ7RLQq+HtahlEVzZtbIcF+Wv/32UdSc3ZxIylJxw4fVHCVpy1tDg4OCq7ylA7vz9hl6YSE67px44bc8ng8rDJxh6TERB3Yv0/VqtewtDk4OKhatRraE/6XDSuDRP/YM/rGftE3kpOtC7B3q1atkpubm1VbcnKy1XJYWJjatGmjnj17SpKCgoI0adIk1a1bV1OmTJGrq6s6depkWb9YsWKaNGmSnnzyScXHx8vNzU3e3jc/zc6XL1+qqwhpKVy4sNXyyZMnFRISYtU2bdo0eXp6auPGjWrevHlGD/meEhMTNWfOHPn6+kq6efVm27ZtOn/+vGX41dixY7V8+XItXrxYXbp0SbWPhIQEJSQkWLWZk5NkcsxhWJ0Pg7ebi5wcHXTh0nWr9guXElTCzz3NbZZt+0febi5a0be+TJJyODlo9oYITVpz8BFUnH1cuhinlJRkeXpZXxny9PLWmX9OZGgf82dMlrdPXgVXeeohVIi0xMbFKjk5WT4+1gHdx8dHx48fs1FVuIX+sV/0jf2ibwgY91S/fn1NmTLFqm3r1q16/fXXLcvh4eHas2eP5s+fb2kzm81KSUnR8ePHVaZMGe3cuVNDhw5VeHi4YmNjlZKSIkk6deqUypYtm+m6fv/9d+XJk8ey7OXlpXPnzmnQoEHasGGDzp8/r+TkZF29elWnTp3K9P7vxt/f3xIupJvHHx8fn+pEunbtmiIiItLcR1hYmIYNG2bVlrtyK7k98bKhtdqDGiV91aNZafWbv0u7jscoMJ+bRrSupP89e13jVx+wdXn4f8u/naXNG9Zq6NipcnY2bp4SAADZDQHjHnLnzq0SJUpYtZ0+fdpqOT4+Xl27dlX37t1TbV+0aFFduXJFjRs3VuPGjTV//nz5+vrq1KlTaty48X1Pkg4MDEx1paN9+/aKjo7WxIkT5e/vLxcXF1WvXj3Dr+Hg4CCz2WzVlpSUlGq93LlzWy3Hx8erQIEC2rBhQ6p107sa079/f/Xq1cuqLajn6gzVaUsx8Qm6kZwiX3dXq3Zfdxedv+Oqxi0fhJbT4j9P6ptNJyRJB/+9pFzOTvqkbRVNWHNAd7zluE/uHp5ycHBU3B0TuuNiY+TplfbwtVtWfjdXy7+dpcGjv5B/saCHWSbu4OXpJUdHx1QTH6Ojo5U3b14bVYVb6B/7Rd/YL/qGORiGqFKlivbv368SJUqkejg7O+vgwYOKjo7Wxx9/rNq1a6t06dKWCd63ODs7S0o9/CozNm/erO7du6tZs2YqV66cXFxcFBUVleHtfX19dfnyZavJ6Rn5jowqVaro7NmzcnJySnX86Z1ILi4ucnd3t3rY+/AoSUpKNmvPyTjVLpPP0mYySbXK5NOOiLTvDJHT2VEpd4SI5P9PFaY01sf9ccqRQ8VKltbft03QTklJ0d9/bVfJshXS3W7FwtlaMm+GBoyarOKlMn81EQ8mh7OzypQtp61//mFpS0lJ0datf6hCxco2rAwS/WPP6Bv7Rd8QMAzRt29fbdmyRe+++652796tI0eOaMWKFZZJ3kWLFpWzs7MmT56sY8eOaeXKlRoxYoTVPvz9/WUymbRq1SpduHBB8fHxma4jKChIc+fO1YEDB7R161a1adNGOXPmzPD2Tz/9tHLlyqUBAwYoIiJC33zzjWbNmnXP7Ro2bKjq1asrNDRUa9eu1YkTJ7RlyxYNHDhQO3bsyPRx2Lup6w6rTe1AvVzdX0F+eTS6TRXlcnbSt5tPSJImd3pSA1r8dwvadeGRal+3mF54srCK5s2lOmXyqe8L5bRuT2Sq4IEH07xlG61fs1wb1q7S6ZPHNWNSmBKuX1O9xs9Jkj4b/aG++eozy/rLv52lhbO/VLfeHyqfXwHFxUQpLiZK169dtdUhZEtt23fU0sWLtHL5Mh2LiNDI4UN17do1hbZ40dalQfSPPaNv7Fd27xuGSBmgQoUK2rhxowYOHKjatWvLbDarePHiat26taSbVwZmzZqlAQMGaNKkSapSpYrGjh2r559/3rKPQoUKadiwYerXr586duyodu3aZeiP+9t99dVX6tKli6pUqaIiRYpo1KhR6t27d4a39/b21rx589SnTx9Nnz5dDRo00NChQ9OcpH07k8mkNWvWaODAgerYsaMuXLggPz8/1alTR/nz58/UMWQFK3aclk8eF33wQln5urtq3z8X9erETYq6fHPSeiHvXEq5bdzT+NUHZJZZ/ULLy88zp6IvJ2jdnjMKW7bPVofw2KpR7xldiovVotlfKi42WgHFS2rAqMmWIVJR58/KZPrvc5V1q5boRlKSxg3va7Wfl9q+qZfbdX2ktWdnTZo2U2xMjL74bJKioi6oVOky+mLqDPlkk6EE9o7+sV/0jf3K7n1jMt856B6wEb83F9u6BKTjp8GNbV0C0lGqYJ57rwQAgEFcM3B5giFSAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhTGaz2WzrIgBJun7D1hUgPV5Pdbd1CUhH7LZJti4BAJCNuDrdex2uYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgZCMnTpyQyWTS7t27JUkbNmyQyWRSXFycTesCAADA44OA8RB06NBBJpNJH3/8sVX78uXLZTKZHmjfs2bNkslkSvWYMWPGPbctUqSIIiMjVb58+Qeq4XHz7Tfz1bRRiJ6sHKw2r7TS3j177rr+2p9+0AvNm+jJysFqGfqcfv9to9XzZrNZn0+eqAZ1a+mpKhXU5Y0OOnnyhOX5f/89rSGDB6jpMyF6qkoFPdukob74bJKSEhNT7Wf2zK/0XLPGqlqpvBrWr63pU6cYdtzZTc0qxbV4Qhcd+2mEru2apOfqBdu6JNwms+ch7u5R/16TpOlTp6hdm1f09BMVVata1XRfa8WypXqpxXN6snKw6tWurlEjht33cYJz50HY4jy5GBen/h+8rxpPVVGtalU1ZPAAXb1yxfL8v/+eVsVypVI99oTvtqyz5LtF6tD2NdWq/qRqVX9SXd7oYHf9TsB4SFxdXTV69GjFxsYavm93d3dFRkZaPdq0aXPP7RwdHeXn5ycnJyfDakm844/irObHH9Zo7JgwdX37HX373TKVKlVa3bq+oejo6DTX3/3XLvXr875avPiSFi5ervohDdTzvXd05Mhhyzozv5quBfPnatCQoZq3YJFy5sypbl3eUEJCgiTpxLFjSkkxa/CQ4Vq6YrX6fNBf3y36VpMmjrd6rdFhH2npku/0fu8PtHzVD5r02RSVD67w8N6Mx1xuV2ftPfyven78na1LwR0yex7i7mzxe02SkpKS1OiZJmrV+tV0a5sza6YmTxqvTm900dIVqzVtxkzVqFnLuIPPZjh37p+tzpP+fXsr4uhRfTljpiZ9/qV27dih4UM/TPV6076apfUbNlkeZcqWszy3Y/tWNW32rGZ8PUdz53+r/H4F1K1LJ507d87Ad+jBEDAekoYNG8rPz09hYWF3XW/JkiUqV66cXFxcFBAQoE8//fSe+zaZTPLz87N65MyZUz/++KNq1aolT09P+fj4qHnz5oqIiLBsd+cQqTsNHTpUlSpVsmqbMGGCAgICLMsdOnRQaGioPvroIxUsWFClSpWSJP3zzz96+eWX5enpKW9vb73wwgs6ceLEPY/F1ubOnqkXX3pZoS1aqniJEho0ZJhcXV21fOmSNNefP2+OatSqrQ6dOqtY8eJ6t3tPlSlbVt9+M0/SzU8v5s+doze7dlP9kIYqWaq0RoaN0YXz5/XL+p8lSTVr19GIj8JUo2YtFS5SRPVCGqh9h05a//Nay+sci4jQdwsXaOLkL1QvpIEKFy6isuXKq3qNmg//TXlMrd1yQMO+WK2Vv9rXpzzI/HmIu7PF7zVJevvd7mrbvoOCgkqm+TqXLl7U55Mn6KOwMWrW/DkVKVpUJUuVVr2QBsa/CdkE5879s8V5ciwiQps3/a4hw0eqQoWKqvJEVfUbMEg//rBa589bhwMPD0/l9fW1PHLkyGF5LmzMp2r9ahuVLlNGgcWKa+jwkUpJSdG2P/94SO9W5hEwHhJHR0eNGjVKkydP1unTp9NcZ+fOnXr55Zf1yiuvaO/evRo6dKgGDx6sWbNm3ddrXrlyRb169dKOHTu0fv16OTg4qEWLFkpJSXmAI0lt/fr1OnTokNatW6dVq1YpKSlJjRs3Vp48efT7779r8+bNcnNzU5MmTez6CkdSYqIO7N+natVrWNocHBxUrVoN7Qn/K81t9uzerWrVqlu11ahZS3v+P7T9e/q0oqIu6Olq/+0zT548Cq5QMd19SlL85cvy8PCwLG/c8IsKFS6sjRs3qOkzIWraKERDPxyoi8yXwWPmfs5DpM+efq/d6Y8/NislJUXnz51T6HNN1Sikjvr06qGzkZGZOELcwrlz/2x1noSH/6U87u4qV/6/IbpPV68hBweHVEOcerzbTfVqV1f711/Vhl/W3/V4rl+/phs3bsj9tr8jbM24sTJIpUWLFqpUqZKGDBmir776KtXz48aNU4MGDTR48GBJUsmSJbV//3598skn6tChQ7r7vXjxotzc3CzLbm5uOnv2rFq2bGm13tdffy1fX1/t37/f0HkXuXPn1owZM+Ts7CxJmjdvnlJSUjRjxgzLHJOZM2fK09NTGzZs0DPPPJNqHwkJCVaXDCXJ7OgiFxcXw+q8l9i4WCUnJ8vHx8eq3cfHR8ePH0tzm6ioKPn45E21flR01P8/f+FmW97U+4yKikpzn6dOntSCb+apV+++lrbTp/9R5JkzWvfTj/oobIySk5P1yegwvf+/7poxc07mDhSwY/dzHiJ99vJ7LS2n/zmtlBSzZkz/Uh/0G6g8efLos0kT1PXNjlq8dKVy/P//KcgYzp37Z6vzJDoqSt7e3lbPOzk5yd3DQ9H/v32uXLn0fp9+qlSlihxMJv28bq16dn9HEyZ9nu7VvgmfjpVvvnxWgcnWuILxkI0ePVqzZ8/WgQMHUj134MAB1axpPeSlZs2aOnLkiJKTk9PdZ548ebR7927LY8uWLZKkI0eO6NVXX1WxYsXk7u5uGdp06tQp4w5IUnBwsCVcSFJ4eLiOHj2qPHnyyM3NTW5ubvL29tb169ethmjdLiwsTB4eHlaPT0bffTjZ4+jcuXN6u2tnNWrcRC1bvWxpN6eYlZiYqJFho1Xliap68qmnNWzER9q+batO8B8HgCzIbE7RjRtJ6tt/kGrWqq0KFSvp40/G6dTJk9q2bautywPsgpeXt9p16KgKFSqqfHAF9ezVW88+97xmzUz9QbUkfTV9mn78YY3GT/zskX5Iey9cwXjI6tSpo8aNG6t///53vSqRGQ4ODipRokSq9ueee07+/v6aPn26ChYsqJSUFJUvXz7Dw5QcHBxkNput2pKSklKtlzt3bqvl+Ph4PfHEE5o/f36qdX19fdN8rf79+6tXr15WbWbHR3tieHl6ydHRMdWErujoaOXNmzfNbfLmzavo6KjU6///pxp589483uioaPn65rNap1Tp0lbbnT9/Tp07tlPFypX14dAR1q/j6ysnJycFBARa2gKLFZckRUZGKiCwWGYOFbBb93MeIn22/r12N3n///+D4sX/+//L29tbnl5eDJO6D5w7989W54lP3ryKiYmx2seNGzd06eJF+eRN++8lSQoOrqg////D5NvNnvmVZn41TVNnzFTJUhk/Fx8FrmA8Ah9//LG+//57/fGH9eSbMmXKaPPmzVZtmzdvVsmSJeXo6Jip14iOjtahQ4c0aNAgNWjQQGXKlMn0Hax8fX119uxZq5CR3oTw21WpUkVHjhxRvnz5VKJECauHRzrjAV1cXOTu7m71eNTJO4ezs8qULaett02KSklJ0datf6hCxcppblOhUiVt/fNPq7Y//9iiCv8/Ob5Q4cLKm9dXW7f+t8/4+Hjt3RNutc9z587pjQ7tVLZsOQ0fGSYHB+tTsVLlKrpx44b+ue3q08n/nzRfoGDB+zpewB7dz3mI9Nny99q9VKpcRZJ04sRxS9vFuDjFxcbye+0+cO7cP1udJxUrVtblS5e0f9/flnW2bf1TKSkpCq6Q/l0iDx08YAnot8z8arqmffmFvpg6w2pOh70gYDwCwcHBatOmjSZNmmTV/v7772v9+vUaMWKEDh8+rNmzZ+uzzz5T7969M/0aXl5e8vHx0bRp03T06FH98ssvqa4Q3Eu9evV04cIFjRkzRhEREfr888/1ww8/3HO7Nm3aKG/evHrhhRf0+++/6/jx49qwYYO6d++e7gR3e9G2fUctXbxIK5cv07GICI0cPlTXrl1TaIsXJUkD+3+gieP/u7NXm9fbacvm3zV71tc6fixCUz6frH1//61XXntd0s07fLVp207Tp07Rhl/W68jhQxrU/wP55sunkAYNJd0MF507tFWBAgXUq09fxcbEKOrCBUVduGB5nWrVa6hM2XIaMniADhzYr/37/taIYR+qWo2aVlc1kHG5czqrQslCqlCykCQpoJCPKpQspCJ+XjauDPc6D5E5tvi9JkmRZ87o4IEDiow8o+TkZB08cEAHDxyw3OM/ICBQ9UMaaHTYR9r91y4dOXJYgwb0U0BgMT351NOP7g16jHDu3D9bnCfFihdXzVq1NWzIYO3ds0d/7dqpsI9GqEnTZ5UvX35J0srly/TD6lU6fixCx49FaMa0L7V82RK92uZ1Sy1fz5imzydP1LARo1SwYCHL3xC3f5+GrTFE6hEZPny4Fi5caNVWpUoVLVq0SB9++KFGjBihAgUKaPjw4fc1lMrBwUHffvutunfvrvLly6tUqVKaNGmS6tWrl+F9lClTRl988YVGjRqlESNGqGXLlurdu7emTZt21+1y5cql3377TX379tWLL76oy5cvq1ChQmrQoIHc3d0zfSyPUpOmzRQbE6MvPpukqKgLKlW6jL6YOkM+/3+J9GxkpBxM/+XwSpWrKGzMWH02aYImTxinov4BmjD5c6vbMnZ8401du3ZNw4d+qMuXL6lylSf0xdQZlis0f27ZrFOnTurUqZN6JqSOVT3h+w5Jutmfkz6foo8/GqlO7dooZ85cqlm7jnr36Svcnypli2rt9O6W5THv3/xPZO7KreoyNPXwPjw69zoPkTm2+L0mSV98NkkrVyyzLLd+KVSSNGPmHEuAGBk2Rp+MHqV33+4qB5ODnnjySU2ZOsPqFpzIOM6d+2er8yRs9FiFfTRCXd5oLwcHBzVo9Iz69R9kVdu0L7/QmcgzcnJ0VEBgMY0ZO16NGjexPP/dwm+VlJSk9//X3Wq7t95+V93eec/Q9+l+mcx3DroHbOT6DVtXgPR4PdX93ivBJmK3Tbr3SgAAGMQ1A5cnGCIFAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABjGZDabzbYuApCk1X+ft3UJSEdQXjdbl4B0jPr1qK1LwF182aqCrUsAAEO5Ot17Ha5gAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWA8QrNmzZKnp6dNazCZTFq+fLkk6cSJEzKZTNq9e7dNawIAAMDjw8nWBfzzzz8aMmSIfvzxR0VFRalAgQIKDQ3Vhx9+KB8fH5vWtmHDBtWvX1+xsbGGBIPWrVurWbNmhtR0p4EDB2rkyJH33D4yMlJeXl4PVEN2tOmHpfp1xQJdjotRwYDiavFGT/kHlU1z3T1/btTPS+cqKvJfpSTfUN4ChVXvudaqWq+J1Tpb1q7Q6YhDuhp/Se+P/VqFAoMe1eE8VlYvW6il385WbEy0AouXVNcefVWyTPk01z15PELzv/5CEYcP6PzZSHV+t7deaNXGap1vZn6pBbOmWrUVKhqgL+cue2jH8LhqEOSjpqV95ZHTSadir2vezn91POZamuvWCvRS52pFrNqSklP05qK/01y/fdVCqh/ko292ndHaQ1GG1w5r334zX7NnfqWoqAsqWaq0+g0YrOAKFWxdFkTf2LPs3Dc2DRjHjh1T9erVVbJkSS1YsECBgYHat2+f+vTpox9++EF//vmnvL29H9rrJyUlKUeOHA+8n8TERDk7O99zvZw5cypnzpwP/HqSdOjQIbm7u1uW3dzcMrSdn5+fIa9/S0aPPSv7a/N6rZj1mVp1fV9Fg8rqt1XfadqI99Vv8jfK45E6rOVyc1fDlu2Uv1BROTrl0P4dW/Tt5x/LzcNLpSs/LUlKvH5NgaWDValGfS2aMuZRH9Jj4/dfftKMzz/VO70GqmTZ8lr53Tf6sPfb+nLecnl6pf7dkXD9uvwKFlateo0047NP091v0cDiGvnpl5ZlB0fHh1L/4+ypoh56pXIBzd7+r45FX9UzpfKqd/1A9Vt1SJcTktPc5mpisvqvPmRZNqez7yqF3VU8by7FXk16CJXjTj/+sEZjx4Rp0JBhCg6uqPlzZ6tb1ze0YtWPNv8gMLujb+xXdu8bmw6Reuedd+Ts7Ky1a9eqbt26Klq0qJo2baqff/5Z//77rwYOHChJGjBggJ5++ulU21esWFHDhw+3LM+YMUNlypSRq6urSpcurS+++MLy3K3hQAsXLlTdunXl6uqq+fPn6+TJk3ruuefk5eWl3Llzq1y5clqzZo1OnDhhuVLg5eUlk8mkDh06SJLq1aund999Vz179lTevHnVuHFjSdK4ceMUHBys3Llzq0iRInr77bcVHx9vqeHOIVJDhw5VpUqVNHfuXAUEBMjDw0OvvPKKLl++fM/3Ll++fPLz87M83NzctH37djVq1Eh58+aVh4eH6tatq127dlltd/sQqTulNYRr+fLlMplMqWqeMWOGAgMD5erqKkmKi4tT586d5evrK3d3d4WEhCg8PPyex5EVbPx+oao1fE5PhTwrvyKBeqlrb+VwcdW29avTXL9E+cqq8HQd5S8coLx+hVSneSsV8C+m4wf3WtapWq+JGr/cUSUrVH1Uh/FYWr5onho3f1ENm72gogHF9fb7A+Xi6qp1a5anuX7JMuXUqdv/VKdBE+VwTv/DBUdHR3n55LU8PDy56pdZjUv5amNEjDYdj9WZSwmavf1fJd4wq06xu39odPH6Dcvj0vUbqZ73zOmk158oqC+3nFJySnoRBEaaO3umXnzpZYW2aKniJUpo0JBhcnV11fKlS2xdWrZH39iv7N43NgsYMTEx+umnn/T222+n+lTfz89Pbdq00cKFC2U2m9WmTRtt27ZNERERlnX27dunPXv26LXXXpMkzZ8/Xx9++KE++ugjHThwQKNGjdLgwYM1e/Zsq33369dPPXr00IEDB9S4cWO98847SkhI0G+//aa9e/dq9OjRcnNzU5EiRbRkyc0fgkOHDikyMlITJ0607Gf27NlydnbW5s2b9eWXNz/pdHBw0KRJk7Rv3z7Nnj1bv/zyiz744IO7vg8RERFavny5Vq1apVWrVmnjxo36+OOP7+s9vXz5stq3b69Nmzbpzz//VFBQkJo1a5ahwJIZR48e1ZIlS7R06VLL/I1WrVrp/Pnz+uGHH7Rz505VqVJFDRo0UExMjKGv/ajdSErS6YjDKlnhCUubg4ODSlaoqhOH991ze7PZrMN7dujCmX9UrGzFh1lqtpOUlKSjhw+o4hP/ffjg4OCgSk88rUP79jzQvs+cPqX2LzZS51eaa+yIATp/LvJBy81WHB1MCvDOqf1n//uAxSxp37nLKp43V7rbuTg5aOzzpfXp86XVvba/Crq7WD1vktSlelH9cOCCzlxKeEjV43ZJiYk6sH+fqlWvYWlzcHBQtWo1tCf8LxtWBvrGftE3NhwideTIEZnNZpUpUybN58uUKaPY2FhduHBB5cqVU8WKFfXNN99o8ODBkm4GiqefflolSpSQJA0ZMkSffvqpXnzxRUlSYGCg9u/fr6lTp6p9+/aW/fbs2dOyjiSdOnVKLVu2VHBwsCSpWLFiluduDc/Kly9fqk/2g4KCNGaM9dCWnj17Wv4dEBCgkSNH6q233rK6knKnlJQUzZo1S3ny5JEktW3bVuvXr9dHH32U7jaSVLhwYavlkydPKiQkxKpt2rRp8vT01MaNG9W8efO77i8zEhMTNWfOHPn6+kqSNm3apG3btun8+fNycbn5B8HYsWO1fPlyLV68WF26dEm1j4SEBCUkWP+BkJSYoBzOLqnWtaUrly8qJSVZeTytP3XN4+Gl8/+eTHe7a1fiNazLi7qRlCgHB0e1fLOXSlV88mGXm61cuhirlORked0xFMrTy0enT5247/2WLFNePfsNV6Gi/oqNjtKCWVPV771O+mzWYuXKlfsBq84e8rg4ytHBpIt3XIG4dP2GCuRxTXObyEsJ+mrrPzodd105cziqaRlfDWpUQgPXHFbstZtDoZqV9VVKilnrDkc/9GPATbFxsUpOTk41pMPHx0fHjx+zUVWQ6Bt7Rt/YwSRvszljl7jbtGmjr7/+WoMHD5bZbNaCBQvUq1cvSdKVK1cUERGhN954Q2+++aZlmxs3bsjDw8NqP1WrWg9J6d69u7p166a1a9eqYcOGatmypSpkYALOE088kart559/VlhYmA4ePKhLly7pxo0bun79uq5evapcudL+1C4gIMASLiSpQIECOn/+/D1f//fff7fazsvLS+fOndOgQYO0YcMGnT9/XsnJybp69apOnTp1z/1lhr+/vyVcSFJ4eLji4+NTnUjXrl2zuup0u7CwMA0bNsyq7dVuvdXm7T6G1morLjlz6f2xXyvx+jUd2btTK2Z9Jp/8BVWifGVbl4Z7qFqtluXfgcVLqmSZYL3Rupk2/bpWzzzbwoaVPd4ioq8qIvqqZflo1BWNeraU6pfw1tK95+TvlVPPlMyrIT8dsWGVAICMsFnAKFGihEwmkw4cOKAWLVL/p33gwAF5eXlZ/pB99dVX1bdvX+3atUvXrl3TP//8o9atW0uSZZ7D9OnTU83VcLxjcmbu3NafQHbu3FmNGzfW6tWrtXbtWoWFhenTTz/Ve++9d9f679zPiRMn1Lx5c3Xr1k0fffSRvL29tWnTJr3xxhtKTExMN2DcOcncZDIpJSXlrq8t3bxCc+dVlfbt2ys6OloTJ06Uv7+/XFxcVL16dSUmJt5zf9LNy3d3Br6kpNSTKO889vj4eBUoUEAbNmxItW56d9/q37+/JSDe8svRixmq81HKncdDDg6OuhxnPdTr8sVY5fFMf5KWg4ODfAvcvMpUKDBI506f0PqlcwkYBnL38JKDo6NiY637Ji42Wl7exk2gc8uTRwULF1Xkv/8Yts/H3eWEZCWnmOXhav1fjLurky5ez9jE7GSzdCr2mvLluXlVs1S+3Mrj6qRPn//vqrejg0mvVCqgZ0rmVe/vDxp3ALDw8vSSo6OjoqOtrxpFR0crb968NqoKEn1jz+gbG87B8PHxUaNGjfTFF1/o2jXr2xaePXtW8+fPV+vWrS0TjAsXLqy6detq/vz5mj9/vho1aqR8+fJJkvLnz6+CBQvq2LFjKlGihNUjMDDwnrUUKVJEb731lpYuXar3339f06dPlyTL3ZGSk9O+48ntdu7cqZSUFH366aeqVq2aSpYsqTNnzmTqPXlQmzdvVvfu3dWsWTOVK1dOLi4uiorK+O0bfX19dfnyZV25csXSlpHvyKhSpYrOnj0rJyenVO9/eieSi4uL3N3drR72NjxKkpxy5FDh4iV1ZO9OS1tKSoqO7NmpgJLlMrwfs9msGze4442RcuTIoRIly2jPzq2WtpSUFIXv2qZS5Yy7DeC1q1d19sxpeXlnj/8UjJCcYtaJmGsq6/ff3e1Mksrmd1NE1NX0N7yNySQV9nRV3P8Pj9p8PFaDfzisD3/87xF7NUk/HLygsRuOP4zDgKQczs4qU7actv75h6UtJSVFW7f+oQoV+cDElugb+0Xf2HiI1GeffaYaNWqocePGGjlypNVtagsVKpRqHkKbNm00ZMgQJSYmavz48VbPDRs2TN27d5eHh4eaNGmihIQE7dixQ7Gxsak+Kb9dz5491bRpU5UsWVKxsbH69ddfLfNC/P39ZTKZtGrVKjVr1kw5c+ZM93awJUqUUFJSkiZPnqznnnvOavL3oxIUFKS5c+eqatWqunTpkvr06ZOp2+I+/fTTypUrlwYMGKDu3btr69atmjVr1j23a9iwoapXr67Q0FCNGTPGEq5Wr16tFi1apBqWltXUfa61FkwepSLFS6toUBltXPWdEhOu6amQm99p8s2kkXL3zqvmr78lSfp56VwVKV5aefMX0o0biTqw60/t2PiTXuryvmWfVy5fUlzUOV2MuRkAz5+5OYwtj6e33L0e/9vXGSX05dc1PuxDlShdViVLl9eKxd/o+rVratj0BUnSuI8Gycc3n9p36S7p5hW5f07cHP96IylJ0VHndezIIbnmzKmChYtKkr76YpyeqlFH+fIXVEz0eX3z9ZdycHBQ3YZN0i4Cafrp0AW9Wa2Ijsdcs9ym1sXJQb8fj5UkvVmtiGKvJWlx+FlJ0vPl8iki+qrOX05ULuebczB8cjnrt4ibV6iuJCbrSqL1hz3JKWZdvH5DZy8z4fthatu+owYP6Kty5cqrfHAFzZs7W9euXVNoixfvvTEeKvrGfmX3vrFpwAgKCtKOHTs0ZMgQvfzyy4qJiZGfn59CQ0M1ZMiQVN+B8dJLL+ndd9+Vo6OjQkNDrZ7r3LmzcuXKpU8++UR9+vRR7ty5FRwcbDXxOi3Jycl65513dPr0abm7u6tJkyaW8FKoUCENGzZM/fr1U8eOHdWuXbt0/+CuWLGixo0bp9GjR6t///6qU6eOwsLC1K5du/t9ezLtq6++UpcuXVSlShUVKVJEo0aNUu/evTO8vbe3t+bNm6c+ffpo+vTpatCggYYOHZrmJO3bmUwmrVmzRgMHDlTHjh114cIF+fn5qU6dOsqfP/+DHpbNVa7ZQPEX4/Tjt1/pUlyMCgWWUJdBYy0Tv2Ojzlndyjfx+nUtmTZOcTHnlcPZRfkL+atNj8GqXLOBZZ192zfp28/DLMtzxw2VJD3zckc1ad3p0RzYY6B2SGNdjIvV/K+nKDYmWsVKlNKwTz63DJG6cP6sTA7/XaiNibqgHp1fsSwv+3aOln07R+UrPaGwiTMkSdEXzmns8P66dOmiPDy9VDa4ksZOmSMPz4f3nTyPo22nLiqPi5NaBOeXh+vNL9r7dMNxy61nfXLlsBqSmdvZUR2fKiwPVyddTUzWiZhrGvnzUe4WZQeaNG2m2JgYffHZJEVFXVCp0mX0xdQZ8skmQz3sGX1jv7J735jMGZhlvWdPxm/5mJEJ0kBaVv9978ntsI2gvBn7Ikc8eqN+PWrrEnAXX7bi/0QAjxfXDFyeyNAVjEqVKslkMqV7x6dbz5lMpgzNVwAAAADweMpQwDh+nAl0AAAAAO4tQwHD39//YdcBAAAA4DFwX7epnTt3rmrWrKmCBQvq5Mmb32Y8YcIErVixwtDiAAAAAGQtmQ4YU6ZMUa9evdSsWTPFxcVZ5lx4enpqwoQJRtcHAAAAIAvJdMCYPHmypk+froEDB1p9S3bVqlW1d+9eQ4sDAAAAkLVkOmAcP35clSun/hZCFxcXq2+ABgAAAJD9ZDpgBAYGavfu3anaf/zxR8s3YAMAAADInjL9Td69evXSO++8o+vXr8tsNmvbtm1asGCBwsLCNGPGjIdRIwAAAIAsItMBo3PnzsqZM6cGDRqkq1ev6rXXXlPBggU1ceJEvfLKKw+jRgAAAABZRKYDhiS1adNGbdq00dWrVxUfH698+fIZXRcAAACALOi+AoYknT9/XocOHZIkmUwm+fr6GlYUAAAAgKwp05O8L1++rLZt26pgwYKqW7eu6tatq4IFC+r111/XxYsXH0aNAAAAALKITAeMzp07a+vWrVq9erXi4uIUFxenVatWaceOHeratevDqBEAAABAFpHpIVKrVq3STz/9pFq1alnaGjdurOnTp6tJkyaGFgcAAAAga8n0FQwfHx95eHikavfw8JCXl5chRQEAAADImjIdMAYNGqRevXrp7NmzlrazZ8+qT58+Gjx4sKHFAQAAAMhaMjREqnLlyjKZTJblI0eOqGjRoipatKgk6dSpU3JxcdGFCxeYhwEAAABkYxkKGKGhoQ+5DAAAAACPgwwFjCFDhjzsOgAAAAA8BjI9BwMAAAAA0pPp29QmJydr/PjxWrRokU6dOqXExESr52NiYgwrDgAAAEDWkukrGMOGDdO4cePUunVrXbx4Ub169dKLL74oBwcHDR069CGUCAAAACCryHTAmD9/vqZPn673339fTk5OevXVVzVjxgx9+OGH+vPPPx9GjQAAAACyiEwHjLNnzyo4OFiS5ObmposXL0qSmjdvrtWrVxtbHQAAAIAsJdMBo3DhwoqMjJQkFS9eXGvXrpUkbd++XS4uLsZWBwAAACBLyXTAaNGihdavXy9Jeu+99zR48GAFBQWpXbt26tSpk+EFAgAAAMg6Mn0XqY8//tjy79atW8vf319btmxRUFCQnnvuOUOLAwAAAJC1PPD3YFSrVk29evXS008/rVGjRhlREwAAAIAsyrAv2ouMjNTgwYON2h0AAACALIhv8gYAAABgGAIGAAAAAMNkepI38LBULORp6xKALOfLVhVsXQLuIqDbYluXgHScmPKSrUsAHlsZDhi9evW66/MXLlx44GIAAAAAZG0ZDhh//fXXPdepU6fOAxUDAAAAIGvLcMD49ddfH2YdAAAAAB4DTPIGAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhrmvgPH777/r9ddfV/Xq1fXvv/9KkubOnatNmzYZWhwAAACArCXTAWPJkiVq3LixcubMqb/++ksJCQmSpIsXL2rUqFGGFwgAAAAg68h0wBg5cqS+/PJLTZ8+XTly5LC016xZU7t27TK0OAAAAABZS6YDxqFDh9L8xm4PDw/FxcUZURMAAACALCrTAcPPz09Hjx5N1b5p0yYVK1bMkKIAAAAAZE2ZDhhvvvmmevTooa1bt8pkMunMmTOaP3++evfurW7duj2MGgEAAABkEU6Z3aBfv35KSUlRgwYNdPXqVdWpU0cuLi7q3bu33nvvvYdRIwAAAIAswmQ2m833s2FiYqKOHj2q+Ph4lS1bVm5ubkbXhmzmdGyirUsAspy8eZxtXQLuIqDbYluXgHScmPKSrUsAsiTXDFyeyPQVjFucnZ1VtmzZ+90cAAAAwGMo0wGjfv36MplM6T7/yy+/PFBBAAAAALKuTAeMSpUqWS0nJSVp9+7d+vvvv9W+fXuj6gIAAACQBWU6YIwfPz7N9qFDhyo+Pv6BCwIAAACQdWX6NrXpef311/X1118btTsAAAAAWZBhAeOPP/6Qq6urUbsDAAAAkAVleojUiy++aLVsNpsVGRmpHTt2aPDgwYYVBgAAACDryXTA8PDwsFp2cHBQqVKlNHz4cD3zzDOGFQYAAAAg68lUwEhOTlbHjh0VHBwsLy+vh1UTAAAAgCwqU3MwHB0d9cwzzyguLu4hlQMAAAAgK8v0JO/y5cvr2LFjD6MWAAAAAFlcpgPGyJEj1bt3b61atUqRkZG6dOmS1QMAAABA9pXhORjDhw/X+++/r2bNmkmSnn/+eZlMJsvzZrNZJpNJycnJxlcJAAAAIEvIcMAYNmyY3nrrLf36668Psx4AAAAAWViGA4bZbJYk1a1b96EVAwAAACBry9QcjNuHRAEAAADAnTIVMEqWLClvb++7PmDfTCaTli9fLkk6ceKETCaTdu/ebdOaAAAA8PjI1BftDRs2LNU3eWdVHTp00OzZsyVJOXLkUNGiRdWuXTsNGDBATk6Z/oLzR2bDhg2qX79+qvaBAwdq5MiR99w+MjKSL0k0wPLFC7Ro3izFxESpeIlSeu/9/ipdLjjNdU8cO6pZ0z7X4YP7de7sGb3d8wO1fKXtI644+6BvsqZvv5mv2TO/UlTUBZUsVVr9BgxWcIUKti4rW+lYr7jeblxSvh6u2v/PRQ1c8Jf+OhGb7vpvNiih9vWKq5B3LsXEJ2jVzn81auleJdxIeYRVg3PHfmXnvsnUX9KvvPKK8uXL97BqeeSaNGmimTNnKiEhQWvWrNE777yjHDlyqH///rYuTYmJiXJ2dk73+UOHDsnd3d2y7ObmlqH9+vn5PXBtt7tXnY+jX9f9qC8nfqKefQerdLkKWvrtXPXt2VWzFn4vL2+fVOtfv35dBQoVVp0Gz2jKhDE2qDj7oG+yph9/WKOxY8I0aMgwBQdX1Py5s9Wt6xtasepH+fik7jcY74WqhTX05QrqO2+Xdh2P0ZsNg7SgZ23VGvyToi4npFq/xVNFNLBlsP43a4d2RESrWP48mtixqswya+iiPTY4guyJc8d+Zfe+yfAQqcdx/oWLi4v8/Pzk7++vbt26qWHDhlq5cqUkKTY2Vu3atZOXl5dy5cqlpk2b6siRI5JuTnj39fXV4sWLLfuqVKmSChQoYFnetGmTXFxcdPXqVUlSXFycOnfuLF9fX7m7uyskJETh4eGW9YcOHapKlSppxowZCgwMlKur611rz5cvn/z8/CwPNzc3bd++XY0aNVLevHnl4eGhunXrateuXVbb3T5E6k6zZs2Sp6enVdvy5cut+j69Ou91fI+TxQvmqNkLLdWkeQsFBBZXz74fysU1p35ctSzN9UuXLa+u772vkEZNlSNH9gpjjxp9kzXNnT1TL770skJbtFTxEiU0aMgwubq6avnSJbYuLdvo2qik5v9+XN9uOanDkZf1wbxdupaYrFdqBqS5/pPFfbT9aLSWbftH/0Rf1cb957R82z+qHMBQ6UeJc8d+Zfe+yXDAuHUXqcdZzpw5lZiYKOnmEKodO3Zo5cqV+uOPP2Q2m9WsWTMlJSXJZDKpTp062rBhg6SbYeTAgQO6du2aDh48KEnauHGjnnzySeXKlUuS1KpVK50/f14//PCDdu7cqSpVqqhBgwaKiYmxvP7Ro0e1ZMkSLV269L7mRVy+fFnt27fXpk2b9OeffyooKEjNmjXT5cuXH+yNuUNadWbk+B4HSUlJOnxov6o8Wc3S5uDgoCpPVtP+vY9noMoq6JusKSkxUQf271O16jUsbQ4ODqpWrYb2hP9lw8qyjxyOJlXw99RvB85b2sxm6fcD51S1eNqftG6PiFYFf09VDrg55LZo3twKCfbT+r/PPpKawbljz+ibTAyRSkl5fMdUms1mrV+/Xj/99JPee+89HTlyRCtXrtTmzZtVo8bNH4758+erSJEiWr58uVq1aqV69epp6tSpkqTffvtNlStXlp+fnzZs2KDSpUtrw4YNllv6btq0Sdu2bdP58+fl4uIiSRo7dqyWL1+uxYsXq0uXLpJuDjeaM2eOfH1971lz4cKFrZZPnjypkJAQq7Zp06bJ09NTGzduVPPmzR/sTbrNnXVm9Phul5CQoISEhDvaTJbt7dXFuFilJCenGm7j5eWjf04ct1FVkOibrCo2LlbJycmphgz4+Pjo+PFjNqoqe/F2c5GTo4MuXLpu1X7hUoJK+Lmnuc2ybf/I281FK/rWl0lSDicHzd4QoUlrDj6CiiFx7tgz+iaTd5F63KxatUpubm5ydXVV06ZN1bp1aw0dOlQHDhyQk5OTnn76acu6Pj4+KlWqlA4cOCDp5veB7N+/XxcuXNDGjRtVr1491atXTxs2bFBSUpK2bNmievXqSZLCw8MVHx8vHx8fubm5WR7Hjx9XRESE5TX8/f0zFC4k6ffff9fu3bstDy8vL507d05vvvmmgoKC5OHhIXd3d8XHx+vUqVPGvWlp1JnR47tdWFiYPDw8rB6fj2cMPABkBTVK+qpHs9LqN3+XGo38WR2/2KIGwQX0v2fL2Lo0AHbAfm+X9AjUr19fU6ZMkbOzswoWLJipu0cFBwfL29tbGzdu1MaNG/XRRx/Jz89Po0eP1vbt25WUlGS5+hEfH68CBQpYhlTd7vY5D7lz587w6wcGBqaaL9G+fXtFR0dr4sSJ8vf3l4uLi6pXr24Z9nUvDg4OqYbCJSUlpVrvzjozeny369+/v3r16mXVduGq/c/z8fD0koOjo2Jjoq3aY2Oj5Z0NJm3ZM/oma/Ly9JKjo6Oio637LTo6Wnnz5rVRVdlLTHyCbiSnyNfdeu6fr7uLzt9xVeOWD0LLafGfJ/XNphOSpIP/XlIuZyd90raKJqw5oGwwqtrmOHfsF32Tza9g5M6dWyVKlFDRokWtwkWZMmV048YNbd261dIWHR2tQ4cOqWzZspJuTpauXbu2VqxYoX379qlWrVqqUKGCEhISNHXqVFWtWtXyh3iVKlV09uxZOTk5qUSJElYPI3/QNm/erO7du6tZs2YqV66cXFxcFBUVleHtfX19dfnyZV25csXSlpG5IPdzfC4uLnJ3d7d62PvwKOnmLY1Lliqrv7b/97ORkpKiv7b/qbLBFW1YGeibrCmHs7PKlC2nrX/+YWlLSUnR1q1/qELFyjasLPtISjZrz8k41S7z310iTSapVpl82hERneY2OZ0dlXJHiEj+/1Rh/x8VPR44d+wXfZPNA0Z6goKC9MILL+jNN9/Upk2bFB4ertdff12FChXSCy+8YFmvXr16WrBggSpVqiQ3Nzc5ODioTp06mj9/vmX+hSQ1bNhQ1atXV2hoqNauXasTJ05oy5YtGjhwoHbs2GFo3XPnztWBAwe0detWtWnTRjlz5szw9k8//bRy5cqlAQMGKCIiQt98841mzZp1z+0e1fHZi5debafVK5fop9UrdPL4MU0YM0LXr19T42dDJUkfDxugGV9MsKyflJSko4cP6ujhg7pxI0lRF87r6OGD+vcfY4eugb7Jqtq276ilixdp5fJlOhYRoZHDh+ratWsKbfGirUvLNqauO6w2tQP1cnV/Bfnl0eg2VZTL2Unfbj4hSZrc6UkNaFHesv668Ei1r1tMLzxZWEXz5lKdMvnU94VyWrcnMlXwwMPDuWO/snvfZOshUnczc+ZM9ejRQ82bN1diYqLq1KmjNWvWKEeOHJZ16tatq+TkZMtcC+lm6FixYoVVm8lk0po1azRw4EB17NhRFy5ckJ+fn+rUqaP8+fMbVvNXX32lLl26qEqVKipSpIhGjRql3r17Z3h7b29vzZs3T3369NH06dPVoEEDDR06NM1J2rd7VMdnL+o3aqKLcTGaNf1zxUZHqXhQaX08/kt5+9y8WnP+bKTVrX2jL5xX13atLMuL5s/SovmzVLFyVY2bMvOR1/84o2+ypiZNmyk2JkZffDZJUVEXVKp0GX0xdYZ8sslQAnuwYsdp+eRx0QcvlJWvu6v2/XNRr07cZPkOjELeuZRy27in8asPyCyz+oWWl59nTkVfTtC6PWcUtmyfrQ4hW+LcsV/ZvW9M5uxw/1lkCadjMzZXBMB/8ubh+zvsWUC3xfdeCTZxYspLti4ByJJcM3B5giFSAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhTGaz2WzrIgBJun7D1hUgPV5PvmvrEpCO2O2f2boEAEA24up073W4ggEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAcZ9MJpOWL19u6zIyZdasWfL09LQsDx06VJUqVbJZPQAAAHj8ZNmA0aFDB5lMJplMJuXIkUOBgYH64IMPdP36dVuX9lDdfty3P44ePXrPbVu3bq3Dhw8/giqzt2+/ma+mjUL0ZOVgtXmllfbu2WPrkiCpZpXiWjyhq46t/UjX/vpMz9WrYOuScBvOG/tG/9gv+sZ+Zee+ybIBQ5KaNGmiyMhIHTt2TOPHj9fUqVM1ZMgQW5f10N067tsfgYGB99wuZ86cypcvn6G1JCYmGrq/rO7HH9Zo7JgwdX37HX373TKVKlVa3bq+oejoaFuXlu3lzumivYf/Vc+whbYuBXfgvLFv9I/9om/sV3bvmywdMFxcXOTn56ciRYooNDRUDRs21Lp16yzPR0dH69VXX1WhQoWUK1cuBQcHa8GCBVb7qFevnrp3764PPvhA3t7e8vPz09ChQ63WOXLkiOrUqSNXV1eVLVvW6jVu2bt3r0JCQpQzZ075+PioS5cuio+PtzzfoUMHhYaGatSoUcqfP788PT01fPhw3bhxQ3369JG3t7cKFy6smTNnZvi4b384Ojpq3LhxCg4OVu7cuVWkSBG9/fbbVjXcOUTqTvXq1VPPnj2t2kJDQ9WhQwfLckBAgEaMGKF27drJ3d1dXbp0kSRt2rRJtWvXVs6cOVWkSBF1795dV65cueexPG7mzp6pF196WaEtWqp4iRIaNGSYXF1dtXzpEluXlu2t3bxfw75YpZW/Zp9PkLIKzhv7Rv/YL/rGfmX3vsnSAeN2f//9t7Zs2SJnZ2dL2/Xr1/XEE09o9erV+vvvv9WlSxe1bdtW27Zts9p29uzZyp07t7Zu3aoxY8Zo+PDhlhCRkpKiF198Uc7Oztq6dau+/PJL9e3b12r7K1euqHHjxvLy8tL27dv13Xff6eeff9a7775rtd4vv/yiM2fO6LffftO4ceM0ZMgQNW/eXF5eXtq6daveeustde3aVadPn76v98DBwUGTJk3Svn37NHv2bP3yyy/64IMP7mtfdzN27FhVrFhRf/31lwYPHqyIiAg1adJELVu21J49e7Rw4UJt2rQp1fE/7pISE3Vg/z5Vq17D0ubg4KBq1WpoT/hfNqwMsF+cN/aN/rFf9I39om+yeMBYtWqV3Nzc5OrqquDgYJ0/f159+vSxPF+oUCH17t1blSpVUrFixfTee++pSZMmWrRokdV+KlSooCFDhigoKEjt2rVT1apVtX79eknSzz//rIMHD2rOnDmqWLGi6tSpo1GjRllt/8033+j69euaM2eOypcvr5CQEH322WeaO3euzp07Z1nP29tbkyZNUqlSpdSpUyeVKlVKV69e1YABAxQUFKT+/fvL2dlZmzZtytBx33q0atVKktSzZ0/Vr19fAQEBCgkJ0ciRI1MdqxFCQkL0/vvvq3jx4ipevLjCwsLUpk0b9ezZU0FBQapRo4YmTZqkOXPmpDsnJiEhQZcuXbJ6JCQkGF7roxQbF6vk5GT5+PhYtfv4+CgqKspGVQH2jfPGvtE/9ou+sV/0jeRk6wIeRP369TVlyhRduXJF48ePl5OTk1q2bGl5Pjk5WaNGjdKiRYv077//KjExUQkJCcqVK5fVfipUsJ7sWaBAAZ0/f16SdODAARUpUkQFCxa0PF+9enWr9Q8cOKCKFSsqd+7clraaNWsqJSVFhw4dUv78+SVJ5cqVk4PDf5kuf/78Kl++vGXZ0dFRPj4+lte+13Hfcut1f/75Z4WFhengwYO6dOmSbty4oevXr+vq1aupjvlBVK1a1Wo5PDxce/bs0fz58y1tZrNZKSkpOn78uMqUKZNqH2FhYRo2bJhV28DBQzTow6GG1QkAAIBHL0sHjNy5c6tEiRKSpK+//loVK1bUV199pTfeeEOS9Mknn2jixImaMGGCZW5Cz549U01MzpEjh9WyyWRSSkqK4fWm9Tr389q3H/ctJ06cUPPmzdWtWzd99NFH8vb21qZNm/TGG28oMTExQwHDwcFBZrPZqi0pKSnN179dfHy8unbtqu7du6dat2jRomm+Vv/+/dWrVy+rNrOjyz1rtGdenl5ydHRMNYErOjpaefPmtVFVgH3jvLFv9I/9om/sF32TxYdI3c7BwUEDBgzQoEGDdO3aNUnS5s2b9cILL+j1119XxYoVVaxYsUzfprVMmTL6559/FBkZaWn7888/U60THh5uNal58+bNcnBwUKlSpR7gqDJu586dSklJ0aeffqpq1aqpZMmSOnPmTKb24evra3WcycnJ+vvvv++5XZUqVbR//36VKFEi1eP2OTG3c3Fxkbu7u9XDxSVrB4wczs4qU7actv75h6UtJSVFW7f+oQoVK9uwMsB+cd7YN/rHftE39ou+eYwChiS1atVKjo6O+vzzzyVJQUFBWrdunbZs2aIDBw6oa9euVnMiMqJhw4YqWbKk2rdvr/DwcP3+++8aOHCg1Tpt2rSRq6ur2rdvr7///lu//vqr3nvvPbVt29YyPOphK1GihJKSkjR58mQdO3ZMc+fO1ZdffpmpfYSEhGj16tVavXq1Dh48qG7duikuLu6e2/Xt21dbtmzRu+++q927d+vIkSNasWJFtpvkLUlt23fU0sWLtHL5Mh2LiNDI4UN17do1hbZ40dalZXu5czqrQslCqlCykCQpoJCPKpQspCJ+XjauDJw39o3+sV/0jf3K7n2TpYdI3cnJyUnvvvuuxowZo27dumnQoEE6duyYGjdurFy5cqlLly4KDQ3VxYsXM7xPBwcHLVu2TG+88YaeeuopBQQEaNKkSWrSpIllnVy5cumnn35Sjx499OSTTypXrlxq2bKlxo0b9zAOM00VK1bUuHHjNHr0aPXv31916tRRWFiY2rVrl+F9dOrUSeHh4WrXrp2cnJz0v//9T/Xr17/ndhUqVNDGjRs1cOBA1a5dW2azWcWLF1fr1q0f5JCypCZNmyk2JkZffDZJUVEXVKp0GX0xdYZ8ssklUXtWpay/1s7oYVke0/vmfK25K/9UlyHzbFUWxHlj7+gf+0Xf2K/s3jcm852D7gEbuX7D1hUgPV5PZr+rUVlF7PbPbF0CACAbcc3A5YnHaogUAAAAANsiYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwTrYuAEAW4Ffc1hUgHTHxibYuAXfh7eZs6xIA4JHjCgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYJhsGTA6dOig0NBQW5fxyM2aNUuenp6W5aFDh6pSpUo2qwcAAACPH7sMGCaT6a6PoUOH2rpEm+nQoUOa78nRo0fvuW3r1q11+PDhR1Bl9vbtN/PVtFGInqwcrDavtNLePXtsXdJjrWvzijo4q5NiV7yn38a/oqol86e7rpOjg/q/9rT2fd1RsSve09bPX1ejJ/yt1qlZvpAWD31Bx+a9qWs//E/PVS/+sA/hsbHsuwV6JbSxnqn9hLp1ek0H9u296/ob1v+kdi8/p2dqP6FOr7XQn5t/s3o+JjpKHw8fqJeeDVGTOk/qgx5v6fSpk1brfL/sO/Xs1lHP1q+m+k8HK/7yJcOPC/xes2f0jf3Kzn1jlwEjMjLS8pgwYYLc3d2t2nr37m3rEh+6xMTEdJ9r0qSJ1fsRGRmpwMDAe+4zZ86cypcvn5Fl3rXO7OjHH9Zo7JgwdX37HX373TKVKlVa3bq+oejoaFuX9lh6qU5Jje5SRx/N/1PV35uvPcejtHLki/L1yJnm+kPb11DnphXUa8qvqtx1jmas2aOFg59XxeK+lnVyu+bQ3mMX1POLXx7VYTwWfln3o6ZM/ETt33hL02YvUvESJfVBj66KjUn7Z//vPbs1YnBfNXvuRU2f851q1QnR4A966HjEEUmS2WzW4A96KPLf0xr5ySRNm7tI+f0KqPd7b+ratauW/SRcv66nqtVUmw6dH8lxZkf8XrNf9I39yu59Y5cBw8/Pz/Lw8PCQyWSyLOfLl0/jxo1T4cKF5eLiokqVKunHH3+02n7v3r0KCQlRzpw55ePjoy5duig+Pj5Dr202m+Xr66vFixdb2ipVqqQCBQpYljdt2iQXFxddvXrzP7m4uDh17txZvr6+cnd3V0hIiMLDwy3rR0RE6IUXXlD+/Pnl5uamJ598Uj///LPV6wYEBGjEiBFq166d3N3d1aVLl3RrdHFxsXqP/Pz85OjoqHHjxik4OFi5c+dWkSJF9Pbbb1sd951DpO5Ur1499ezZ06otNDRUHTp0uGedmzZtUu3atZUzZ04VKVJE3bt315UrV9J9rcfV3Nkz9eJLLyu0RUsVL1FCg4YMk6urq5YvXWLr0h5L3VtU0cwf/tbcdft18FSM3pv8s64l3FD7Z8qnuf5rIWU0ZuE2/bT9hE6cvajpq/fop+3H1ePFJyzrrN1xQsPmbNHKLRGP6jAeC98tmKNnX2ipps+1UECx4urV70O5uubUD98vS3P9JQvn6alqNfVK247yDyymTm+9p6BSZbXsuwWSpNP/nNT+v/eoZ9/BKl22vIr6B+p/fQcrISFBv6z9wbKfl15tq9fad1bZ8hUfyXFmR/xes1/0jf3K7n1jlwHjbiZOnKhPP/1UY8eO1Z49e9S4cWM9//zzOnLk5qdeV65cUePGjeXl5aXt27fru+++088//6x33303Q/s3mUyqU6eONmzYIEmKjY3VgQMHdO3aNR08eFCStHHjRj355JPKlSuXJKlVq1Y6f/68fvjhB+3cuVNVqlRRgwYNFBMTI0mKj49Xs2bNtH79ev31119q0qSJnnvuOZ06dcrqtceOHauKFSvqr7/+0uDBgzP93jg4OGjSpEnat2+fZs+erV9++UUffPBBpvdzL3fWGRERoSZNmqhly5bas2ePFi5cqE2bNmX4PX9cJCUm6sD+fapWvYalzcHBQdWq1dCe8L9sWNnjKYeTgyoH5dcvu/87j8xm6Zfdp/RUmQJpbuOcw1HXE29YtV1LvKEa5Qo+1Fofd0lJSTp8cL+eeKqapc3BwUFVnqymfXvD09xm/95wPfFkNau2J6vVsKyf9P9XR52dXaz2mSNHDu0N32X0ISAd/F6zX/SN/aJvsmDAGDt2rPr27atXXnlFpUqV0ujRo1WpUiVNmDBBkvTNN9/o+vXrmjNnjsqXL6+QkBB99tlnmjt3rs6dO5eh16hXr54lYPz222+qXLmyVduGDRtUt25dSTc/ud+2bZu+++47Va1aVUFBQRo7dqw8PT0tV0EqVqyorl27qnz58goKCtKIESNUvHhxrVy50up1Q0JC9P7776t48eIqXjz9cd+rVq2Sm5ub5dGqVStJUs+ePVW/fn0FBAQoJCREI0eO1KJFizL61mbYnXWGhYWpTZs26tmzp4KCglSjRg1NmjRJc+bM0fXr19PcR0JCgi5dumT1SEhIMLzWRyk2LlbJycny8fGxavfx8VFUVJSNqnp85XXPKSdHB52PvWrVfj72qvy8cqW5zc87T6r7i0+oeEFPmUxSSOWieqFGCfl5534UJT+2LsbFKiU5WV7e1j/7Xt4+iklniFRMdFSa68dG3zxXigYEKr9fAU3/YoIuX7qopKQkLZjzlS6cP6dozqdHht9r9ou+sV/0TRYLGJcuXdKZM2dUs2ZNq/aaNWvqwIEDkqQDBw6oYsWKyp07t9XzKSkpOnToUIZep27dutq/f78uXLigjRs3ql69epaAkZSUpC1btqhevXqSpPDwcMXHx8vHx8fqj/7jx48rIuLmEIv4+Hj17t1bZcqUkaenp9zc3HTgwIFUVzCqVq2aofrq16+v3bt3Wx6TJk2SJP38889q0KCBChUqpDx58qht27aKjo62DOUyyp11hoeHa9asWVbH37hxY6WkpOj48eNp7iMsLEweHh5Wj09GhxlaJ3Cn3lM3KOLfWIVPa69L3/fQ+Lfra866fUpJsXVluJOTUw4N+3i8Tp86qecb1VKTuk/qr53b9XT1WnJwMNm6PADAXTjZugB7FBwcLG9vb23cuFEbN27URx99JD8/P40ePVrbt29XUlKSatS4edkrPj5eBQoUsFzduN2t+Q69e/fWunXrNHbsWJUoUUI5c+bUSy+9lGqC9O2h6G5y586tEiVKWLWdOHFCzZs3V7du3fTRRx/J29tbmzZt0htvvKHExETLcK67cXBwkNlstmpLSkpK8/VvFx8fr65du6p79+6p1i1atGiar9W/f3/16tXLqs3s6JLmulmFl6eXHB0dU03gio6OVt68eW1U1eMr6tI13UhOUb47rlbk88qls7Fph+qoi9f08ojv5ZLDUT7urjoTfUUjO9XS8bMXH0XJjy0PTy85ODqmmtAdGxMt7zuuUtzi7ZM3zfW9fP47V0qVKacZ8xYrPv6ybiQlydPLW906vaZSpcsafxBIE7/X7Bd9Y7/omyx2BcPd3V0FCxbU5s2brdo3b96ssmVv/odTpkwZhYeHW00w3rx5sxwcHFSqVKkMvY7JZFLt2rW1YsUK7du3T7Vq1VKFChWUkJCgqVOnqmrVqpY/sqtUqaKzZ8/KyclJJUqUsHrc+iHavHmzOnTooBYtWig4OFh+fn46ceKEAe/If3bu3KmUlBR9+umnqlatmkqWLKkzZ85kah++vr6KjIy0LCcnJ+vvv/++53ZVqlTR/v37Ux1/iRIl5OzsnOY2Li4ucnd3t3q4uGTtgJHD2VllypbT1j//sLSlpKRo69Y/VKFiZRtW9nhKupGiv46cU/1KRSxtJpNUv1IRbTsQeZctpYSkZJ2JviInRweF1gzSqj+Y0P0gcuTIoZKly2rX9q2WtpSUFO3a/qfKBac9+bpscEXt2rHVqm3ntj/SXN/NLY88vbx1+tRJHT6wTzXrhBh7AEgXv9fsF31jv+ibLBYwJKlPnz4aPXq0Fi5cqEOHDqlfv37avXu3evToIUlq06aNXF1d1b59e/3999/69ddf9d5776lt27bKnz/9++PfqV69elqwYIEqVaokNzc3OTg4qE6dOpo/f75l/oUkNWzYUNWrV1doaKjWrl2rEydOaMuWLRo4cKB27NghSQoKCtLSpUu1e/duhYeH67XXXlOKwWMySpQooaSkJE2ePFnHjh3T3Llz9eWXX2ZqHyEhIVq9erVWr16tgwcPqlu3boqLi7vndn379tWWLVv07rvvavfu3Tpy5IhWrFiR7SZ5S1Lb9h21dPEirVy+TMciIjRy+FBdu3ZNoS1etHVpj6VJy3apY5NgtWlYVqWKeGvSuw2UyyWH5qzbJ0ma8X5jDe/w35DKJ0v56YUaJRTg56Ga5Qpp5cgWcjCZNG7xDss6uV1zqEIxX1UodvPWtQH53VWhmK+K+OZ5tAeXxbR6tZ1WrViiH1ev0MnjxzR+9Ahdv35NTZqHSpJGDR2g6Z9PsKzfsvXr2vbHZi2aP1unThzTrOlf6NCBfWrR6lXLOhvW/6TdO7frzL//aNPGX9S7exfVrBOiJ6v9N3EyJjpKRw8f1L+nbw45PXb0iI4ePqhLF7kqZRR+r9kv+sZ+Zfe+yXJDpLp3766LFy/q/fff1/nz51W2bFmtXLlSQUFBkqRcuXLpp59+Uo8ePSx3emrZsqXGjRuXqdepW7eukpOTLXMtpJuhY8WKFVZtJpNJa9as0cCBA9WxY0dduHBBfn5+qlOnjiXQjBs3Tp06dVKNGjWUN29e9e3bV5cuGftlUBUrVtS4ceM0evRo9e/fX3Xq1FFYWJjatWuX4X106tRJ4eHhateunZycnPS///1P9evXv+d2FSpU0MaNGzVw4EDVrl1bZrNZxYsXV+vWrR/kkLKkJk2bKTYmRl98NklRURdUqnQZfTF1hnyyySXRR23xb4eV1yOnPny9uvJ759KeiAt6YfAynY+7OUSqSL48Srlt2J+Ls6OGtK+hQD8PxV9L0k/bj+uNT37UxSv/3WCgSlB+rR3TyrI8pms9SdLcdfvUZdzaR3NgWVBIoya6GBejWdM+V0x0lIqXLK3RE76U9/8PeTp/LtJq7kT5CpU0aMTH+vrLzzRjykQVKuKvEWMmKrB4kGWd6KgofTHhE8XGRMsnr6+eafqc2r7xltXrrly6SLNnTLEs93irgySp7+ARlnCDB8PvNftF39iv7N43JvOdg+4BG7l+497rwDa8nhtv6xKQjogF79i6BNyFt1vaw0QBIKtyzcDliSw3RAoAAACA/SJgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAEDAAAAACGIWAAAAAAMAwBAwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwAAAAABiGgAEAAADAMAQMAAAAAIYhYAAAAAAwDAEDAAAAgGEIGAAAAAAMQ8AAAAAAYBgCBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMAAACAYQgYAAAAAAxDwAAAAABgGAIGAAAAAMMQMAAAAAAYhoABAAAAwDAms9lstnURwOMkISFBYWFh6t+/v1xcXGxdDu5A/9gv+sZ+0Tf2jf6xX9m1bwgYgMEuXbokDw8PXbx4Ue7u7rYuB3egf+wXfWO/6Bv7Rv/Yr+zaNwyRAgAAAGAYAgYAAAAAwxAwAAAAABiGgAEYzMXFRUOGDMlWk7myEvrHftE39ou+sW/0j/3Krn3DJG8AAAAAhuEKBgAAAADDEDAAAAAAGIaAAQAAAMAwBAwAAAAAhiFgAAAAADAMAQMwQFxcnGbMmKH+/fsrJiZGkrRr1y79+++/Nq4MknTjxg39/PPPmjp1qi5fvixJOnPmjOLj421cGTh37Bd9Y/8SExN16NAh3bhxw9al4A7ZvW+4TS3wgPbs2aOGDRvKw8NDJ06c0KFDh1SsWDENGjRIp06d0pw5c2xdYrZ28uRJNWnSRKdOnVJCQoIOHz6sYsWKqUePHkpISNCXX35p6xKzLc4d+0Xf2LerV6/qvffe0+zZsyXJ8nvtvffeU6FChdSvXz8bV5h90Tc3cQUDeEC9evVShw4ddOTIEbm6ulramzVrpt9++82GlUGSevTooapVqyo2NlY5c+a0tLdo0ULr16+3YWXg3LFf9I1969+/v8LDw7Vhwwar/mnYsKEWLlxow8pA39zkZOsCgKxu+/btmjp1aqr2QoUK6ezZszaoCLf7/ffftWXLFjk7O1u1BwQEMNTDxjh37Bd9Y9+WL1+uhQsXqlq1ajKZTJb2cuXKKSIiwoaVgb65iSsYwANycXHRpUuXUrUfPnxYvr6+NqgIt0tJSVFycnKq9tOnTytPnjw2qAi3cO7YL/rGvl24cEH58uVL1X7lyhWrP2rx6NE3NxEwgAf0/PPPa/jw4UpKSpIkmUwmnTp1Sn379lXLli1tXB2eeeYZTZgwwbJsMpkUHx+vIUOGqFmzZrYrDJw7doy+sW9Vq1bV6tWrLcu3/nCdMWOGqlevbquyIPrmFiZ5Aw/o4sWLeumll7Rjxw5dvnxZBQsW1NmzZ1W9enWtWbNGuXPntnWJ2do///yjJk2ayGw268iRI6pataqOHDmivHnz6rfffkvzkyY8Gpw79ou+sW+bNm1S06ZN9frrr2vWrFnq2rWr9u/fry1btmjjxo164oknbF1itkXf3ETAAAyyefNmhYeHKz4+XlWqVFHDhg1tXRL+340bN7Rw4UKr/mnTpo3VpG/YDueO/aJv7NexY8cUFhZm1T99+/ZVcHCwrUvL9ugbAgbwQJKSkpQzZ07t3r1b5cuXt3U5uENSUpJKly6tVatWqUyZMrYuB7fh3LFf9I19S0pKUteuXTV48GAFBgbauhzchr75D3MwgAeQI0cOFS1aNM1JxLC9HDly6Pr167YuA2ng3LFf9I19y5Ejh5YsWWLrMpAG+uY/BAzgAQ0cOFADBgywfNMt7Ms777yj0aNHZ9tvU7VnnDv2i76xb6GhoVq+fLmty0Aa6JubGCIFPKDKlSvr6NGjSkpKkr+/f6rJj7t27bJRZZD++0I9Nzc3BQcHp+qfpUuX2qgycO7YL/rGvo0cOVKffvqpGjRooCeeeCJV/3Tv3t1GlYG+uYkv2gMeUGhoqK1LwF14enpyW007xbljv+gb+/bVV1/J09NTO3fu1M6dO62eM5lM2eaPWHtE39zEFQwAAAAAhmEOBgAAAADDMEQKeEAODg6Wb+pMC3disa3AwMC79s+xY8ceYTW4HeeO/aJv7FunTp3u+vzXX3/9iCrBneibmwgYwANatmyZ1XJSUpL++usvzZ49W8OGDbNRVbilZ8+eVsu3+ufHH39Unz59bFMUJHHu2DP6xr7FxsZaLSclJenvv/9WXFycQkJCbFQVJPrmFuZgAA/JN998o4ULF2rFihW2LgVp+Pzzz7Vjxw7NnDnT1qXgDpw79ou+sV8pKSnq1q2bihcvrg8++MDW5eA22bFvCBjAQ3Ls2DFVqFBB8fHxti4FaTh27JgqVaqkS5cu2boU3IFzx37RN/bt0KFDqlevniIjI21dCu6Q3fqGSd7AQ3Dt2jVNmjRJhQoVsnUpSMfixYvl7e1t6zJwB84d+0Xf2L+IiAi+VNROZbe+YQ4G8IC8vLysJkOazWZdvnxZuXLl0rx582xYGaSbXxh2Z/+cPXtWFy5c0BdffGHDysC5Y7/oG/vWq1cvq2Wz2azIyEitXr1a7du3t1FVkOibWxgiBTygWbNmWf1H7ODgIF9fXz399NPy8vKyYWWQlGpC6q3+qVevnkqXLm2jqiBx7tgz+sa+1a9f32r5Vv+EhISoU6dOcnLi82NboW9uImAAAAAAMEz2iFGAwfbs2ZPhdStUqPAQK0FaMjNx293d/SFWgjtx7tgv+gaAUbiCAdyHW19Cda/Tx2Qy8YVUNnCvLwmTbo6LpX8ePc4d+0Xf2Lc755Pdza5dux5yNbgdfZMaVzCA+3D8+HFbl4C7+PXXX21dAtLBuWO/6Bv7FhoaausSkA76JjWuYAAAAAAwDFcwgPuwcuVKNW3aVDly5NDKlSvvuu7zzz//iKrCLXv27FH58uXl4OBwz3HljCV/tDh37Bd9A8AoXMEA7oODg4POnj2rfPnyycEh/e+rZKyybdzZP+mNK6d/Hj3OHftF39g3b29vHT58WHnz5k31PSV3iomJeYSVgb5JjSsYwH1ISUlJ89+wD8ePH5evr6/l37AfnDv2i76xb+PHj1eePHkkSRMmTLBtMbBC36TGFQwAAAAAhuEKBmCAK1euaOPGjTp16pQSExOtnuvevbuNqsLt9u/fn2b/MJbctjh37Bd9kzVcv349Vf/w/T72ITv3DVcwgAf0119/qVmzZrp69aquXLkib29vRUVFKVeuXMqXL5+OHTtm6xKztWPHjqlFixbau3ev1VyMW2NkGUtuO5w79ou+sW9XrlxR3759tWjRIkVHR6d6nt9rtkPf3JT+LC4AGfK///1Pzz33nGJjY5UzZ079+eefOnnypJ544gmNHTvW1uVlez169FBgYKDOnz+vXLlyad++ffrtt99UtWpVbdiwwdblZWucO/aLvrFvH3zwgX755RdNmTJFLi4umjFjhoYNG6aCBQtqzpw5ti4vW6Nv/p8ZwAPx8PAwHzx40PLv/fv3m81ms/nPP/80lypVypalwWw2+/j4mMPDw81ms9ns7u5u6av169ebK1WqZMvSsj3OHftF39i3IkWKmH/99Vez2Ww258mTx3zkyBGz2Ww2z5kzx9y0aVMbVgb65iauYAAPKEeOHJZbOubLl0+nTp2SJHl4eOiff/6xZWnQzcvRt+7ukTdvXp05c0aS5O/vr0OHDtmytGyPc8d+0Tf2LSYmRsWKFZN0c0z/rVuf1qpVS7/99pstS8v26JubmOQNPKDKlStr+/btCgoKUt26dfXhhx8qKipKc+fOVfny5W1dXrZXvnx5hYeHKzAwUE8//bTGjBkjZ2dnTZs2zfKfAGyDc8d+0Tf2rVixYjp+/LiKFi2q0qVLa9GiRXrqqaf0/fffy9PT09blZWv0zU1M8gYe0I4dO3T58mXVr19f58+fV7t27bRlyxYFBQXp66+/VsWKFW1dYrb2008/6cqVK3rxxRd19OhRNW/eXIcPH5aPj48WLlyokJAQW5eYbXHu2C/6xr6NHz9ejo6O6t69u37++Wc999xzMpvNSkpK0rhx49SjRw9bl5ht0Tc3ETCA+/Thhx+qX79+ypUrlyQpNjZWXl5eNq4Kt3z99ddq06aNXFxcUj0XExNzz29bxcPDuWO/6Bv7duzYMQUGBqb63XXy5Ent3LlTJUqUUIUKFWxUXfZG31gjYAD3ydHRUZGRkcqXL5+km2Mtd+/ezbAbO3Fn/xQsWFBbtmxRQECAbQsD544do2/s253907p1a02aNEn58+e3cWWgb6wxyRu4T3dmc7K6fbmzPy5fvqyUlBQbVYPbce7YL/rGvt3ZH2vWrNGVK1dsVA1uR99YI2AAAAAAMAx3kQLuk8lk0uXLl+Xq6iqz2SyTyaT4+HhdunTJaj13d3cbVZi9mUwmq7Gwdy7Ddjh37Bd9Y9/S+j3G7zX7QN9YYw4GcJ8cHBysfnnc+s/4zuXk5GRblJftOTg4yMPDw9IncXFxcnd3t9zb/5Zb9yjHo8O5Y7/oG/vm4OCgpk2bWm5e8f333yskJES5c+e2Wm/p0qW2KC9bo2+scQUDuE+//vqrrUvAXcycOdPWJSAdnDv2i76xb+3bt7dafv31121UCe5E31jjCgYAAAAAwzDJGwAAAIBhCBgAAAAADEPAAAAAAGAYAgYAAAAAwxAwgAfUqVMnXb58OVX7lStX1KlTJxtUhPSYzWa+mRi4h6SkJDk5Oenvv/+2dSlAlpKUlKROnTrp+PHjti7F5riLFPCAHB0dFRkZqXz58lm1R0VFyc/PTzdu3LBRZbhlzpw5+uSTT3TkyBFJUsmSJdWnTx+1bdvWxpVlb1euXNHHH3+s9evX6/z580pJSbF6/tixYzaqDMWKFdOyZctUsWJFW5eCdJw5c0abNm1K89zp3r27jaqCh4eHdu/ercDAQFuXYlN8DwZwny5dumT5RPzWN9/ekpycrDVr1qQKHXj0xo0bp8GDB+vdd99VzZo1JUmbNm3SW2+9paioKP3vf/+zcYXZV+fOnbVx40a1bdtWBQoUyNbfemtvBg4cqAEDBmju3Lny9va2dTm4w6xZs9S1a1c5OzvLx8fH6twxmUwEDBsKDQ3V8uXLs/3/LVzBAO7Tnd94eyeTyaRhw4Zp4MCBj7Aq3CkwMFDDhg1Tu3btrNpnz56toUOHcinbhjw9PbV69WpL8IP9qFy5so4ePaqkpCT5+/un+jbiXbt22agySFKRIkX01ltvqX///nJwYLS7PRk5cqQ+/fRTNWjQQE888USqcye7hD+uYAD36ddff5XZbFZISIiWLFli9Smfs7Oz/P39VbBgQRtWCEmKjIxUjRo1UrXXqFFDkZGRNqgIt3h5efHpuJ0KDQ21dQm4i6tXr+qVV14hXNihr776Sp6entq5c6d27txp9Vx2urrEFQzgAZ08eVJFihThF72dKl++vF577TUNGDDAqn3kyJFauHCh9u7da6PKMG/ePK1YsUKzZ89Wrly5bF0OkGV88MEH8vb2Vr9+/WxdCpAmAgZgkKtXr+rUqVNKTEy0aq9QoYKNKoIkLVmyRK1bt1bDhg0tQ3E2b96s9evXa9GiRWrRooWNK8y+KleurIiICJnNZgUEBChHjhxWzzMMx7bi4uK0ePFiRUREqE+fPvL29tauXbuUP39+FSpUyNblZWvJyclq3ry5rl27puDg4FTnzrhx42xUGXATQ6SAB3ThwgV17NhRP/zwQ5rPJycnP+KKcLuWLVtq69atGj9+vJYvXy5JKlOmjLZt26bKlSvbtrhsjmE49mvPnj1q2LChPDw8dOLECb355pvy9vbW0qVLderUKc2ZM8fWJWZrYWFh+umnn1SqVClJSjXJG7Z1+vRprVy5Ms0PHbNL+OMKBvCA2rRpo5MnT2rChAmqV6+eli1bpnPnzlkmej377LO2LhEAMqVhw4aqUqWKxowZozx58ig8PFzFihXTli1b9Nprr+nEiRO2LjFb8/Ly0vjx49WhQwdbl4I7rF+/Xs8//7yKFSumgwcPqnz58jpx4oTMZrOqVKmiX375xdYlPhIMGgce0C+//KJx48apatWqcnBwkL+/v15//XWNGTNGYWFhti4PADJt+/bt6tq1a6r2QoUK6ezZszaoCLdzcXHh7mt2qn///urdu7f27t0rV1dXLVmyRP/884/q1q2rVq1a2bq8R4aAATygK1euWL7vwsvLSxcuXJAkBQcHM4bchhwcHOTo6HjXh5MTo0QfNW9vb0VFRUn67y5S6T1gOy4uLrp06VKq9sOHD8vX19cGFeF2PXr00OTJk21dBtJw4MABy23RnZycdO3aNbm5uWn48OEaPXq0jat7dPjfFXhApUqV0qFDhxQQEKCKFStq6tSpCggI0JdffqkCBQrYurxsa9myZek+98cff2jSpEmpvv0WD9/48eOVJ08eSdKECRNsWwzS9fzzz2v48OFatGiRpJvj+k+dOqW+ffuqZcuWNq4O27Zt0y+//KJVq1apXLlyqSZ5L1261EaVIXfu3JZ5FwUKFFBERITKlSsnSZYPV7ID5mAAD2jevHm6ceOGOnTooJ07d6pJkyaKiYmRs7OzZs2apdatW9u6RPy/Q4cOqV+/fvr+++/Vpk0bDR8+XP7+/rYuC7A7Fy9e1EsvvaQdO3bo8uXLKliwoM6ePavq1atrzZo1qb48DI9Wx44d7/r8zJkzH1EluFNoaKieffZZvfnmm+rdu7dWrFihDh06aOnSpfLy8tLPP/9s6xIfCQIGYLCrV6/q4MGDKlq06P+1d+dxNef7H8Bfp2hTSSnaRaFoQQ/E3ERRuvcyGGYsIzSWq8EoBoNrMlSMpS5N3MEkIzuRLTLK0tjGVNMtoZuxZmwN7arv74+m85sjS0xzPsc9r+fj0ePR+X6/zveVHpzzPp/ljebNm4uOQwBu376NBQsWYOPGjfD19UV4eDg6duwoOhb9TllZWZ3dVgwNDQWloVqnTp1CZmYmioqK0LlzZ/j4+IiORKTS/vvf/6KoqAguLi4oLi5GSEgI0tLS4ODggBUrVqjNh1osMIgaSEVFBfLz89GmTRvO7VcRv/76K8LCwrBq1Sq4ublhyZIl+Mtf/iI6Fv2muLgYs2bNwvbt2/HgwYM657nFszhlZWXQ0dERHYNe4d69e8jNzQVQM12X62NIVXCRN9EfVFJSgsDAQOjp6aFDhw64fv06AGDKlCmIiIgQnE59LV26FK1bt8b+/fuxZcsWpKWlsbhQMZ9++im+++47xMTEQFtbG+vWrUNoaCgsLCzYZ0EwIyMjeHp6Yv78+fjuu+9QWloqOhL9TnFxMcaNGwdzc3N4enrC09MTFhYWCAwMRElJieh4aq+wsBDr1q3DnDlz8PDhQwA1jUNv3bolOJnycASD6A+aNm0aTp8+jcjISPj5+SEzMxOtW7fG3r178fnnn+PHH38UHVEtaWhoQFdXFz4+PtDU1HzhdVwMKY6NjQ3i4uLg5eUFQ0NDXLx4Efb29ti0aRO2bNmCgwcPio6otk6dOoUTJ04gJSUFaWlpqKyshLu7O3r16gUvLy/07dtXdES1NnHiRCQnJ2P16tXy7WpPnTqFqVOnom/fvoiJiRGcUH0926QyNzcXrVu3xrx589SqSSULDKI/yNbWFtu2bUP37t0VGlJdvXoVnTt3fu5Wj/TnGzNmTL062nIxpDj6+vrIzs6GjY0NrKyssHv3bnTt2hX5+flwdnZGUVGR6IgEoLKyEufPn8fatWuxefNmVFdXc/qaYM2bN8fOnTvh5eWlcPz48eMYNmyYfLt0Uj42qazBieJEf9C9e/fkfTB+r7i4uF5vcOnPERsbKzoCvULr1q2Rn58PGxsbtG/fHtu3b0fXrl2RmJgIIyMj0fHU3uXLl5GSkiL/Ki8vx9/+9rc6b2pJ+UpKStCiRYs6x83MzDhFSrDaYvxZ6takkmswiP4gd3d3HDhwQP64tqhYt24dPDw8RMUiUnljx45FRkYGAGD27NmIjo6Gjo4Opk+fjpkzZwpOp94sLS3RvXt3HD58GN27d8ehQ4dw//597NmzB9OmTRMdT+15eHhgwYIFKCsrkx8rLS1FaGgoX3cEY5PKGhzBIPqDwsLC0L9/f2RnZ6OyshJRUVHIzs5GWloaUlNTRccjUlnTp0+Xf+/j44NLly7hhx9+gL29PVxcXAQmI1NTU1y6dAkFBQUoKCjA3bt3UVpaCj09PdHRCEBUVBR8fX1hZWUFV1dXAEBGRgZ0dHSQlJQkOJ16Y5PKGlyDQdQA8vLyEBERgYyMDPl+8bNmzYKzs7PoaEQq6enTp/Dz88OaNWvg4OAgOg49R2FhIU6cOIHU1FSkpqYiOzsbbm5u6N27NxYvXiw6ntorKSnB5s2bcenSJQCAo6MjRo4cCV1dXcHJ1BubVNZggUFEREKYmprKG1CR6nrw4AFSUlKwd+9ebNmyhYu8iepB3ZtUssAgekP13R2K3YiJnm/69OnQ1tZmvxgVtHv3bvni7uzsbBgbG+Odd96Bl5cXevXqJZ+WQ8qzb9++el87YMCAPzEJvQybVNZggUH0hjQ0NF66S5QkSZDJZPykj+gFpkyZgri4ODg4OKBLly51pg6sWLFCUDIyMzODp6envKDgdE/xNDQU9+WRyWR49i1c7WsSX3fE0dHRQdeuXdGrVy/07t0bHh4eajltjYu8id7Q8ePH5d9LkgR/f3+sW7cOlpaWAlMRvT2ysrLQuXNnADU7rJDq+OWXX0RHoGdUV1fLv09OTsasWbMQFhYm3zXq+++/x7x58xAWFiYqIqHmd1PbpHLlypVq26SSIxhEDeT3DXWIiN52VVVVSEhIQE5ODgDAyckJAwcOhKampuBk1LFjR6xZswbvvPOOwvGTJ09iwoQJ8t8ZiaXOTSo5gkFEREKMGzcOUVFRMDAwUDheXFyMKVOmYMOGDYKS0dWrV+Hv749bt26hXbt2AIDw8HBYW1vjwIEDaNOmjeCE6i0vL++5zSibNm2qNp2iVRmbVHIEg6jBcASD6PVoamrizp07MDMzUzh+//59tGzZEpWVlYKSkb+/PyRJwubNm2FsbAygZjepUaNGQUNDQ6G5KCmfp6cndHR0sGnTJnlH77t372L06NEoKytjDyaBLC0tUVpaCi8vL/kaJhcXl5eu2fxfxBEMogakbv+BEL2Jx48fQ5IkSJKEJ0+eKOy4UlVVhYMHD9YpOki5UlNTcebMGXlxAQAmJiaIiIhAz549BSYjANiwYQMGDRoEGxsbWFtbAwBu3LgBBwcHJCQkiA2n5tiksgYLDKI3NHjwYIXHZWVlmDRpUp2dcHbv3q3MWEQqz8jICDKZDDKZDG3btq1zXiaTITQ0VEAyqqWtrY0nT57UOV5UVAQtLS0Biej37O3tkZmZiaNHjyo02vPx8eEHXYKlp6crNKn87LPP1LJJJadIEb2hsWPH1uu6b7755k9OQvR2SU1NhSRJ6NOnD3bt2qXwKbmWlhZsbW1hYWEhMCGNHj0aFy9exPr169G1a1cAwNmzZzF+/Hh06dIFsbGxYgMSvQXUuUklCwwiIhLi559/ho2NDT9xVUGFhYUICAhAYmIiGjduDKBmR5wBAwYgNjYWTZs2FZyQjh07hmPHjuGXX35R2MIWADdIEIhNKmuwwCAiIiEOHz4MfX19+Vab0dHR+Prrr+Hk5ITo6Gg0a9ZMcEK6evWqfMtTR0dH2NvbC05EABAaGoqFCxfC3d0d5ubmdYr0PXv2CEpGbFJZgwUGEREJ4ezsjCVLlsDf3x8//fQT3N3dERISguPHj6N9+/acXihAdXU1vvzyS+zbtw8VFRXw9vbGggUL1LITsSozNzfH0qVL8eGHH4qOQvRcGq++hIiIqOHl5+fDyckJALBr1y78/e9/R1hYGKKjo3Ho0CHB6dTT4sWL8dlnn0FfXx+WlpaIiopCUFCQ6Fj0jIqKCvTo0UN0DKIXYoFBRERCaGlpoaSkBACQnJyMfv36AQCMjY3x+PFjkdHUVlxcHL766iskJSUhISEBiYmJ8g7EpDo++ugjxMfHi45B9ELcppaIiITo2bMngoOD0bNnT5w7dw7btm0DUNMF18rKSnA69XT9+nX4+/vLH9due3r79m3+TlRIWVkZ/v3vfyM5ORkuLi7yhfi1VqxYISgZUQ0WGEREJER0dDSCgoKwc+dOxMTEwNLSEgBw6NAh+Pn5CU6nniorKxUaHwJA48aN8fTpU0GJ6HkyMzPh5uYGAMjKylI4x13ZSBVwkTcRESldZWUl4uPj0a9fP7Rs2VJ0HPqNhoYG+vfvD21tbfmxxMRE9OnTR6GJKBuIEtHLsMAgIiIh9PT0kJOTA1tbW9FR6DdsIEr0+gYPHlzva9WlOOcUKSIiEqJr16748ccfWWCoEBYOb48LFy5g+/btuH79OioqKhTOqcubWFXBxpN1scAgIiIhJk+ejJCQENy8eRNdunRRmIIDAC4uLoKSEam2rVu3YvTo0fD19cWRI0fQr18/XL58GXfv3sWgQYNEx1M7LMzr4hQpIiISQkOj7k7pMpkMkiRBJpOhqqpKQCoi1efi4oKJEyciKCgIBgYGyMjIgJ2dHSZOnAhzc3OEhoaKjqj27t27h9zcXABAu3btYGpqKjiRcrHAICIiIX7++eeXnufUKaLna9KkCf7zn/+gVatWMDExQUpKCpydnZGTk4M+ffrgzp07oiOqreLiYkyZMgVxcXHy/jGampoYPXo0Vq1aBT09PcEJlYNTpIiISAgWEERvplmzZnjy5AkAwNLSEllZWXB2dkZhYaG8eSWJERwcjNTUVCQmJqJnz54AgFOnTmHq1KkICQlBTEyM4ITKwU7eREQkzKZNm9CzZ09YWFjIRzQiIyOxd+9ewcmIVJenpyeOHj0KABg6dCimTZuG8ePHY/jw4fD29hacTr3t2rUL69evR//+/WFoaAhDQ0P4+/vj66+/xs6dO0XHUxoWGEREJERMTAyCg4Ph7++PwsJC+ZoLIyMjREZGig1HpMJWr16NDz74AAAwd+5cBAcH4+7duxgyZAjWr18vOJ16KykpQYsWLeocNzMzU6vRJa7BICIiIZycnBAWFoZ3331XvlC1devWyMrKgpeXF+7fvy86ItFbp7S0FLq6uqJjqC1vb2+YmJggLi4OOjo6AGp+JwEBAXj48CGSk5MFJ1QOrsEgIiIh8vPz0alTpzrHtbW1UVxcLCAR0durvLwc0dHRWLp0KQoKCkTHUVtRUVHw9fWFlZUVXF1dAQAZGRnQ0dFBUlKS4HTKwylSREQkhJ2dHdLT0+scP3z4MBwdHZUfiEjFlZeXY86cOXB3d0ePHj2QkJAAoKYPg52dHVauXInp06eLDanmOnbsiCtXriA8PBxubm5wc3NDREQErly5gg4dOoiOpzQcwSAiIiGCg4MRFBSEsrIySJKEc+fOYcuWLQgPD8e6detExyNSOf/85z+xdu1a+Pj4IC0tDUOHDsXYsWNx5swZrFixAkOHDoWmpqbomGpPT08P48ePFx1DKBYYREQkxEcffQRdXV3MmzcPJSUlGDFiBCwsLBAVFSVfwEpE/2/Hjh2Ii4vDgAEDkJWVBRcXF1RWViIjIwMymUx0PPpNXl4eIiMjkZOTAwDo0KEDpk6dijZt2ghOpjxc5E1ERMKVlJSgqKgIZmZmoqMQqSwtLS3k5+fD0tISAKCrq4tz587B2dlZcDKqlZSUhAEDBsDNzU3eB+P06dPIyMhAYmIi+vbtKzihcrDAICIiIRYtWoSRI0fCzs5OdBSit4KmpiYKCgpgamoKADAwMEBmZib/DamQTp06wdfXFxEREQrHZ8+ejSNHjuDixYuCkikXCwwiIhLC1dUVWVlZ6NatG0aNGoVhw4ahefPmomMRqSwNDQ30798f2traAIDExET06dMHTZo0Ubhu9+7dIuIRAB0dHfz0009wcHBQOH758mW4uLigrKxMUDLl4i5SREQkREZGBjIzM+Hl5YVly5bBwsICf/3rXxEfH69WDamI6isgIABmZmZo2rQpmjZtilGjRsHCwkL+uPaLxDE1NX3u7njp6elqNQWUIxhERKQSTp8+jfj4eOzYsQNlZWV4/Pix6EhERPWycOFCzJgxA8uWLcPKlSsxe/Zs9OjRA0DN/21LlixBcHAw5s+fLzipcrDAICIilZCeno5vv/0WW7duxYMHD1BaWio6EhFRvWhqauLOnTswNTVFZGQkli9fjtu3bwMALCwsMHPmTEydOlVtdvtigUFERMLk5+cjPj4e8fHxyM3NRa9evTBixAi89957nOpBRG8NDQ0NFBQUKEyDevLkCYCaxfjqhn0wiIhIiO7du+P8+fNwcXHB2LFjMXz4cPn2m0REb5tnRyfUsbCoxQKDiIiE8Pb2xoYNG+Dk5CQ6ChHRH9a2bdtXToF6+PChktKIxSlSREQk1P379wGAW9QS0VtLQ0MDkZGRr5zaGRAQoKREYrHAICIipSssLMTcuXOxbds2PHr0CADQrFkzfPDBB1i0aBGMjIzEBiQieg3PW4OhzjhFioiIlOrhw4fw8PDArVu3MHLkSDg6OgIAsrOzERsbi2PHjiEtLQ3NmjUTnJSIqH7UZXeo+uIIBhERKdUnn3yCY8eOITk5GS1atFA4V1BQgH79+sHb2xsrV64UlJCI6PVwBEMRCwwiIlKqVq1aYe3atfD19X3u+cOHD2PSpEm4du2acoMREVGD0BAdgIiI1MudO3fQoUOHF57v2LEjCgoKlJiIiIgaEgsMIiJSqubNm790dCI/Px/GxsbKC0RERA2KBQYRESmVr68v5s6di4qKijrnysvLMX/+fPj5+QlIRkREDYFrMIiISKlu3rwJd3d3aGtrIygoCO3bt4ckScjJycFXX32F8vJyXLhwAdbW1qKjEhHRG2CBQURESpefn4/JkyfjyJEjqH0Zkslk6Nu3L1avXg17e3vBCYmI6E2xwCAiImEePXqEK1euAADs7e259oKI6H8ACwwiIiIiImowXORNREREREQNhgUGERERERE1GBYYRERERETUYFhgEBERERFRg2GBQUREamfMmDF499135Y+9vLzwySefKD1HSkoKZDIZCgsL/7R7PPuzvgll5CSi/x0sMIiISCWMGTMGMpkMMpkMWlpasLe3x8KFC1FZWfmn33v37t344osv6nWtst9st2rVCpGRkUq5FxFRQ2gkOgAREVEtPz8/fPPNNygvL8fBgwcRFBSExo0bY86cOXWuraiogJaWVoPcl/03iIgaDkcwiIhIZWhra6Nly5awtbXFP/7xD/j4+GDfvn0A/n+qz+LFi2FhYYF27doBAG7cuIFhw4bByMgIxsbGGDhwIK5duyZ/zqqqKgQHB8PIyAgmJib49NNP8WwLqGenSJWXl2PWrFmwtraGtrY27O3tsX79ely7dg29e/cGADRr1gwymQxjxowBAFRXVyM8PBx2dnbQ1dWFq6srdu7cqXCfgwcPom3bttDV1UXv3r0Vcr6JqqoqBAYGyu/Zrl07REVFPffa0NBQmJqawtDQEJMmTUJFRYX8XH2yExHVF0cwiIhIZenq6uLBgwfyx8eOHYOhoSGOHj0KAHj69Cl8fX3h4eGBkydPolGjRli0aBH8/PyQmZkJLS0tLF++HLGxsdiwYQMcHR2xfPly7NmzB3369HnhfUePHo3vv/8e//rXv+Dq6or8/Hzcv38f1tbW2LVrF4YMGYLc3FwYGhpCV1cXABAeHo5vv/0Wa9asgYODA06cOIFRo0bB1NQUvXr1wo0bNzB48GAEBQVhwoQJuHDhAkJCQv7Q3091dTWsrKywY8cOmJiYIC0tDRMmTIC5uTmGDRum8Pemo6ODlJQUXLt2DWPHjoWJiQkWL15cr+xERK9FIiIiUgEBAQHSwIEDJUmSpOrqauno0aOStra2NGPGDPn5Fi1aSOXl5fI/s2nTJqldu3ZSdXW1/Fh5ebmkq6srJSUlSZIkSebm5tLSpUvl558+fSpZWVnJ7yVJktSrVy9p2rRpkiRJUm5urgRAOnr06HNzHj9+XAIgPXr0SH6srKxM0tPTk9LS0hSuDQwMlIYPHy5JkiTNmTNHcnJyUjg/a9asOs/1LFtbW2nlypUvPP+soKAgaciQIfLHAQEBkrGxsVRcXCw/FhMTI+nr60tVVVX1yv68n5mI6EU4gkFERCpj//790NfXx9OnT1FdXY0RI0bg888/l593dnZWWHeRkZGBq1evwsDAQOF5ysrKkJeXh19//RV37txBt27d5OcaNWoEd3f3OtOkaqWnp0NTU/O1Prm/evUqSkpK0LdvX4XjFRUV6NSpEwAgJydHIQcAeHh41PseLxIdHY0NGzbg+vXrKC0tRUVFBdzc3BSucXV1hZ6ensJ9i4qKcOPGDRQVFb0yOxHR62CBQUREKqN3796IiYmBlpYWLCws0KiR4stUkyZNFB4XFRWhS5cu2Lx5c53nMjU1faMMtVOeXkdRUREA4MCBA7C0tFQ4p62t/UY56mPr1q2YMWMGli9fDg8PDxgYGODLL7/E2bNn6/0corIT0f8uFhhERKQymjRpAnt7+3pf37lzZ2zbtg1mZmYwNDR87jXm5uY4e/YsPD09AQCVlZX44Ycf0Llz5+de7+zsjOrqaqSmpsLHx6fO+doRlKqqKvkxJycnaGtr4/r16y8c+XB0dJQvWK915syZV/+QL3H69Gn06NEDkydPlh/Ly8urc11GRgZKS0vlxdOZM2egr68Pa2trGBsbvzI7EdHr4C5SRET01ho5ciSaN2+OgQMH4uTJk8jPz0dKSgqmTp2KmzdvAgCmTZuGiIgIJCQk4NKlS5g8efJLe1i0atUKAQEBGDduHBISEuTPuX37dgCAra0tZDIZ9u/fj3v37qGoqAgGBgaYMWMGpk+fjo0bNyIvLw8XL17EqlWrsHHjRgDApEmTcOXKFcycORO5ubmIj49HbGxsvX7OW7duIT09XeHr0aNHcHBwwIULF5CUlITLly9j/vz5OH/+fJ0/X1FRgcDAQGRnZ+PgwYNYsGABPv74Y2hoaNQrOxHR62CBQUREby09PT2cOHECNjY2GDx4MBwdHREYGIiysjL5iEZISAg+/PBDBAQEyKcRDRo06KXPGxMTg/feew+TJ09G+/btMX78eBQXFwMALC0tERoaitmzZ6NFixb4+OOPAQBffPEF5s+fj/DwcDg6OsLPzw8HDhyAnZ0dAMDGxga7du1CQkICXF1dsWbNGoSFhdXr51y2bBk6deqk8HXgwAFMnDgRgwcPxvvvv49u3brhwYMHCqMZtby9veHg4ABPT0+8//77GDBggMLalldlJyJ6HTLpRavciIiIiIiIXhNHMIiIiIiIqMGwwCAiIiIiogbDAoOIiIiIiBoMCwwiIiIiImowLDCIiIiIiKjBsMAgIiIiIqIGwwKDiIiIiIgaDAsMIiIiIiJqMCwwiIiIiIiowbDAICIiIiKiBsMCg4iIiIiIGsz/AdL9AnuFcyX9AAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 800x600 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Convert predictions and true labels to class indices\n",
    "y_pred_classes = np.argmax(y_pred, axis=1)\n",
    "y_true_classes = np.argmax(y_test, axis=1)\n",
    "\n",
    "conf_matrix_normalized = confusion_matrix(y_true_classes, y_pred_classes, normalize='true')\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.heatmap(conf_matrix_normalized, annot=True, cmap=\"Blues\", cbar=False, xticklabels=error_names, yticklabels=error_names)\n",
    "plt.xlabel(\"Predicted Label\")\n",
    "plt.ylabel(\"True Label\")\n",
    "plt.title(\"Normalized Confusion Matrix\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
